
// declare login variables
global username
global password

// initialize data line counter
put 2 into dataIndex

// initialize login variables
"Datastore".setLoginVariables 4
global customerNumber,  coType, PO, TagField, DeliveryTerm, DeliveryMethod, WHNumber
global itemCode, quantity, PromoCod, TranctionResonCode, BlanketAgreement, SalesHold, priority, ConfigurationNo

//initialize test variables
"Datastore".SetDataScript7 dataIndex


(************** Login To Application ****************)
"Flows/Application".login username, password
(************** Start Test *********************)
repeat forever
"Datastore".SetDataScript7 dataIndex
//increment counter
put dataIndex + 1 into dataIndex

//break if no more data
//if customerNumber is empty then exit repeat

(************** Order entry ***************)
"Flows/OrderEntry".GenericOrderEntry customerNumber, coType, PO, TagField, DeliveryTerm, DeliveryMethod, TranctionResonCode, SalesHold, priority

(************* To recod CO Number ******************************)
put "Flows/OrderEntry".recordCONumber() into coNumber
set coNumber to coNumber
(**************** To enter Line Details And Configuration ********************)
"Flows/OrderEntry".EnterItemProductQuanConfig itemCode, quantity, ConfigurationNo

(*************** To Apply Blanket  Agreement **********************)
"Flows/OrderEntry".ApplyBlanketAgreement BlanketAgreement

(**************** To Close Order entry Screen ****************************)
"M3/OIS101".closeFromOrderLines

log "Order Number Was:-  "& coNumber&", " && "Customer Number Was:-  "& customerNumber&", " &&"Customer Type was:-  "& coType &", "&&"Sales Hold:-  "&SalesHold&", "&&"PO type was:-  "& PO&", " &&"Tag Field Was:-  "& TagField&", " &&"Delivery term was:-  "& DeliveryTerm&", " &&"Delivery Method was:-  "& DeliveryMethod&", "&&"Priority was:-  "&priority&", " &&"Transcation ResonCode was:-  "& TransactionResonCode&", " &&"Item Number was:-  "& itemCode&", " &&"Quantity was:-  "& quantity &", "&&"Promocode:-  "& PromoCod&", " &&"Configration Number:-  "&ConfigurationNo
end repeat
(******************* To Close the Infor Application *************************)
"Flows/Application".exitApp











