(* 
Name: Data-driven end to end custom bag processing
Description: Driven by an excel spreadsheet of test scenario values, this script executes and end to end custom bag flow on the scenario. 
Author: Himanshu Bhardwaj & Andy Jenkins
 *)

//declare login variables
global username, password

//declare data variables
global dataIndex, custNum, custPO, tag, delTerm
global delMeth, style, color, ConfigCode

//initialize test variables
"DataStore".setGlobalsScript1

//initialize data line counter
put 2 into dataIndex

(************** Start Test ***************)
repeat forever
	
	(************** Set up data *************)
	//skip known bad entries in test data
	put (5,6) into badData //these  are having item code of Accesories
	repeat while dataIndex is in badData
		put dataIndex + 1 into dataIndex
	end repeat
	
	//initialize data variables (sets global data variables and logs them)
	DataStore.setDataScript1 dataIndex
	logData
	
	//increment counter
	put dataIndex + 1 into dataIndex
	
	//break if no more data
	//if custNum is empty then exit repeat
	
	(************** Start flow ****************)
	"Flows/Application".login username, password
	
	(************** Order entry ***************)
	//"Flows/OrderEntry".enterNewOrder custNum, "", custPO
	"Flows/OrderEntry".GenericOrderEntry custNum, "", custPO, tag, delTerm, delMeth, BlnktAgrmnt
	put "Flows/OrderEntry".recordCONumber() into coNum
	"Flows/OrderEntry".enterProduct style, ConfigCode
	
	(************** Exit *********************)
	"Flows/Application".exitApp
	
	logData
	
end repeat