

(************ Declare login variables *****************)

global username
global password

(************* Initialize data line counter ***********************) 

put 2 into dataIndex

(************** Login To Application ****************)
"Datastore".setLoginVariables 3
"Flows/Application".login username, password

(************ Initializing Data Sheet *****************)
set ExcelFile to workbook(ResourcePath("4-Automatic_PO_Rec.xlsx"))
set worksheet to ExcelFile.Worksheet("Sheet1")

Put Cell(worksheet, "A" & dataIndex) into WHNumber
Put Cell(worksheet, "B" & dataIndex) into poNumber
Put Cell(worksheet, "C" & dataIndex) into ItemNumber

(************ To Enter PO Number in SUT *********************)

"M3/PPS300".openpoNumber
"M3/PPS300".poReceipt poNumber, WHNumber
"M3/PPS300".delynoteno poNumber
click "M3/PPS300/Next"

(************ To Get Remaining Quantity from Line Item ********************)

"M3/PPS300".searchlineitem ItemNumber
put "M3/PPS300".captureremainingquantity() into RMquanty

(************* To Enter Recived Quantity and Apply ConfirmUpdate *************************)

"M3/PPS300".EnterRecivedQuan RMquanty
click "M3/PPS300/Actions"
click  "M3/PPS300/ConfirmUpdateF"
click "M3/PPS300/previousbutton"

(************** To Get Receiving Number ********************************)

Put "M3/PPS300".recordReceivingNo() into ReciveNumber
click  "M3/PPS300/XClose"
click "M3/PPS300/Confirmoutput"
click "M3/PPS300/XClose"
//4.Inspection approval
"M3/PPS310".open
click "M3/PPS300/Receivingno_1"
TypeText  controlkey, "a"
TypeText deleteKey
Typetext ReciveNumber
TypeText Return
//need to start scripting from step f of inspection approval
//unable to proceed as no data displayed for line items





















