

(************ Declare login variables *****************)

global username
global password

(************* Initialize data line counter ***********************) 

put 2 into dataIndex

(************** Login To Application ****************)
"Datastore".setLoginVariables 3
"Flows/Application".login username, password

//4.AutomaticPOreceiving


// fetching username,password and po number from excelfile
//set ExcelFile to workbook(ResourcePath("AutomaticPOReceiving.xlsx")) 
//set worksheet to ExcelFile.Worksheet("Sheet1")
set ExcelFile to workbook(ResourcePath("4-Automatic_PO_Rec.xlsx"))
set worksheet to ExcelFile.Worksheet("Sheet1")

Put Cell(worksheet, "A" & dataIndex) into WHNumber
Put Cell(worksheet, "B" & dataIndex) into poNumber
Put Cell(worksheet, "C" & dataIndex) into ItemNumber



//2.Look up PO number

"M3/PPS300".openpoNumber
"M3/PPS300".poReceipt poNumber, WHNumber
"M3/PPS300".delynoteno poNumber
click "M3/PPS300/Next"
//2.a
//need to capture reqired quan from sut"
"M3/PPS300".searchlineitem ItemNumber
put "M3/PPS300".captureremainingquantity() into RMquanty
"M3/PPS300".EnterRecivedQuan RMquanty
(*//3.Enter quantities received
click "M3/PPS300/recievedquantityfield"
TypeText controlKey, "a"
TypeText deleteKey
TypeText RMquanty
TypeText Return
wait 2*)

click "M3/PPS300/Actions"
click  "M3/PPS300/ConfirmUpdateF"
click "M3/PPS300/previousbutton"
Put "M3/PPS300".recordReceivingNo() into ReciveNumber
click  "M3/PPS300/XClose"
click "M3/PPS300/Confirmoutput"
click "M3/PPS300/XClose"
//4.Inspection approval
"M3/PPS310".open
click "M3/PPS300/Receivingno_1"
TypeText  controlkey, "a"
TypeText deleteKey
Typetext ReciveNumber
TypeText Return
//need to start scripting from step f of inspection approval
//unable to proceed as no data displayed for line items





















