//8.Expanding Invoice Validation


(************ Declare login variables *****************)

global username
global password

(************* Initialize data line counter ***********************) 

put 2 into dataIndex


(************* Initializing variables *****************************) 

"Datastore".setLoginVariables 3
(*global customerNumber,  coType, PO, TagField, DeliveryTerm, DeliveryMethod, WHNumber
global itemCode, quantity, PromoCod, TranctionResonCode, BlanketAgreement, SalesHold, priority, ConfigurationNo*)


//initialize test variables
//"Datastore".SetDataScript7 dataIndex

(************** Login To Application ****************)

"Flows/Application".login username, password

(************** Start Test *********************)

(*repeat forever
	"Datastore".SetDataScript7 dataIndex
	(******* increment counter *********)
	put dataIndex + 1 into dataIndex
	
	//break if no more data
	if customerNumber is empty then exit repeat*)

//To capture  variables in window  OIS350

"M3/OIS350".open
put "M3/OIS350".ChangeSortingorder() into ChangeSortingorder
Click "M3/OIS350/Extendedinvno"

//to fetch customer order number,invoice number 
set ExcelFile to workbook(ResourcePath("1-Validation.xlsx")) 
set worksheet to ExcelFile.Worksheet("Sheet4")
Put Cell(worksheet ,"A2") into COnumber
log COnumber

"M3/OIS350".SetCoNumber COnumber
//Click "M3/OIS350/Next"
Put "M3/OIS350".GetInvoiceNumber() into InvoiceNo

//put ReadText(imageLocation("M3/OIS350/InvoiceNo_1")) into InvoiceNo
log InvoiceNo


//to capture invoicedate
Put "M3/OIS350".recordInvoiceDate() into InvoiceDate

//To capture variables in OIS300
"M3/OIS300".open

//To record shipment date
"M3/OIS300".openDeliveryToolboxlink
put "M3/OIS300".recordDepartDate() into DepartDate
Click "M3/OIS300/previousbuttonnew"
//To record order date
Put "M3/OIS300".recordOrderDate() into Orderdate

Put "M3/OIS300".recordwarehousenum() into warehousenum
Click "M3/OIS300/previousbuttonnew"
//to record dellivery number
Put "M3/OIS300".recorddelinumber() into DeliNo

put ReadText(imageLocation("M3/OIS300/DelyNoDrag")) into Delyno
log Delyno
Click "M3/OIS300/previousbuttonnew"


//To record address number,sold to(Delivery address) and ship to(Invoice address))
put "M3/OIS300".openaddresses() into openaddresses
put ReadText(imageLocation("M3/OIS300/Customernumber")) into Customernumber
log Customernumber
put ReadText(imageLocation("M3/OIS300/DelreryAddress")) into Deliveryaddress
log Deliveryaddress
put ReadText(imageLocation("M3/OIS300/DelreryAddress_1")) into Deliveryaddress1
log Deliveryaddress1

put ReadText(imageLocation("M3/OIS300/InvoiceAddress")) into Invoiceaddress
log Invoiceaddress
put ReadText(imageLocation("M3/OIS300/InvoiceAddress_1")) into Invoiceaddress1
log Invoiceaddress1
Click "M3/OIS300/previousbuttonnew"

//to record payment terms and payemnt discount

Click "M3/OIS300/HighlightCO"
RightClick "M3/OIS300/HighlightCO"
click "M3/OIS300/Display_1"
Click "M3/OIS300/Next/Next"

put ReadText(imageLocation("M3/OIS300/PaymentTerms")) into Paymentterms
log paymentterms
put ReadText(imageLocation("M3/OIS300/CashDiscountTerms")) into CashDiscountterms
log CashDiscountterms
Click "M3/OIS300/Next/Next"
//To record customer PO#
put ReadText(imageLocation("M3/OIS300/CustomersPONumber")) into CustomersPOnumber
log CustomersPonumber

Repeat 3 times
	Click "M3/OIS300/previousbuttonnew"
End repeat

//to validate pers1 2 and 3 also item number,shiped qty,U/M,sales price(unitprice)
Click "M3/OIS300/HighlightCO"
Click "M3/OIS300/CONUMBERnew"
put ReadText(imageLocation("M3/OIS300/Sortingorder")) into Sortingorder
log Sortingorder
put ReadText(imageLocation("M3/OIS300/View")) into View
Log View
put ReadText(imageLocation("M3/OIS300/OrdQty")) into ordqty
log ordqty
put ReadText(imageLocation("M3/OIS300/UM")) into UM
log UM
put ReadText(imageLocation("M3/OIS300/SalesPrice")) into Salesprice
log Salesprice
Click "M3/OIS300/previousbuttonnew"
put "M3/OIS300".recordconfigvalues into Configvalues
put ReadText(imageLocation("M3/OIS300/Text")) into Text
log  Text
put ReadText(imageLocation("M3/OIS300/Featuregroup")) into Featuregroup
log Featuregroup
put ReadText(imageLocation( "M3/OIS300/Name")) into Name
log Name

//to record customcharge,netprice

Click "M3/OIS300/previousbuttonnew"
put "M3/OIS300".ChangeView() into ChangeView
put ReadText(imageLocation("M3/OIS300/CstmCharge")) into Cstmcharge
log Cstmcharge
put ReadText(imageLocation("M3/OIS300/NetPrice")) into Netprice
log Netprice






























