
put 2 into dataIndex
repeat Forever
	
	set ExcelFile to workbook(ResourcePath("8-data.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	put Cell(worksheet, "A" & dataIndex) into InvoiceNumber
	Log "Read from Invoice with MetaViewer"
	"Other/MetaViewer".openMV
	"Other/MetaViewer".loginMV "ajenkins", "ajenkins"
	"Other/MetaViewer".lookupMV InvoiceNumber
	--"Other/MetaViewer".lookupMV "904492748"
	--put "Other/MetaViewer".validateInvoice() into test
	put ReadMVdata() into test 
	log test
	"Other/MetaViewer".closeMV
	
	put dataIndex+1 into dataIndex
	//break if no more data
	if InvoiceNumber is empty then exit repeat		
end repeat


--                                                   -x-x-xx-x-x-xx-xx-x
--   Sandbox
-- to workaround before making any changes to the existing function or script

--                                                   -x-x-xx-x-x-xx-xx-x
To ReadMVdata
	click "MetaViewer/PDF/MVFullscreen"
	Wait 5
	WaitFor 45,"MetaViewer/PDF/Titleist"
	put "MetaViewer/PDF/" into path
	
	if ImageFound(2, path&"statement") then LogError "It is Account of Statement !"
	Put ReadValueByX("Invoice No",12)into InvoiceNoPDF
	--set InvoiceNoPDF to ReadText((86,314))
	Log (InvoiceNoPDF  & " is the Invoice Number")
	
	Put ReadValueByX("Invoice Date",12)into InvoiceDatePDF
	Log InvoiceDatePDF &": is Invoice date in PDF"
	Put DateManipulate(InvoiceDatePDF) into InvoiceDatePDF
	
	Put ReadValueByX("Order No",11)into OrderNoPDF
	--set OrderNoPDF to ReadText((90,343))
	Log (OrderNoPDF  & " is the Order Number")
	
	Put ReadValueByX("Whs",11)into WhsPDF
	--set WhsPDF to ReadText((173,343))
	--if WhsPDF is "06Y" then set WhsPDF to "060"
	--if WhsPDF is "06B" then set WhsPDF to "061"
	Log WhsPDF && "is the warehouse number"
	
	Put ReadValueByX("Delivery No",11)into deliveryNumber
	--set deliveryNumber to ReadText((250,343))
	Log deliveryNumber && "is delivery number"
	
	Put ReadValueByX("Customer P.O.",13)into customersPO
	if customersPO = "Customer P.0." then 
		set customersPO to ""
	end if
	Log customersPO && "is Customers PO"
	
	set AccountNo to ReadText((900,343))
	Log (AccountNo & " is the Account No of the Ship Account")
	--------------------------------------------------------------------------------------------------------------------------------
	## to scroll page down -------  ******second half of PDF, Y cordinates changes ********
	
	Click(700,140)
	ScrollWheelDown 10
	wait 10
	(*if ImageFound (2,Text: "Shipped Via")
	Log "Shipped Via Details Present"
	Exit Handler
end if   *)
	if ImageFound(5,Text: "Total Shipped Qty")
		Put ImageLocation(Text: "Total Shipped Qty") into Loc
		set TotlShpdQty to ReadText(Loc+(223,4))
		//checks if Shipment charges are applied at item level
		set Item to ReadText(Loc-(0,28))
		Log Item
		if Item contains "$" or if Item contains "S&H Chg"
			Log Item &" : Found at Item Level"
			put Loc-(0,17) into Loc
		end if
		set ItemDscrptn to ReadText(Loc -(0,30))
		put ManipulateItemDescription(ItemDscrptn) into ItemDscrptn
		
		set ItemCode to ReadText(Loc- (0,56))
		
		put  Loc - (20,56) into ItemLineLoc
		put ItemLineLoc into test
		put item 1 of  test into x
		put item 2 of test into y
		put x as number into x
		put y as number into y
		log x &" is X cordinate of Item Line"
		log y &" is Y Cordinate of Item Line"
		Log ItemLineLoc
		
		set ShipdQty to ReadText(ItemLineLoc+(220,0))
		
		set UM to ReadText(ItemLineLoc+(282,0))
		
		set UnitPrice to ReadText(ItemLineLoc+ (377,0))
		put ManipulatePriceFormat(UnitPrice) into UnitPrice
		
		set Disc1 to ReadText ((525,y),(565,y+18))
		if Disc1 is empty then put 0 into Disc1
		else if Disc1 ends with "%" then delete "%" from Disc1
			else if Disc1 begins with "$" then delete "$" from Disc1
		Log Disc1 &":is Disc 1"
		
		set Disc2 to ReadText(((575,y),(634,y+18)))
		if Disc2 is empty then put 0 into Disc2
		else if Disc2 begins with "$" then delete "$" from Disc2
			else if Disc2 ends with "%" then delete "%" from Disc2
		Log Disc2 &":is Disc 2"
		
		set Disc3 to ReadText (((637,y),(692,y+18)))
		if Disc3 is empty then put 0 into Disc3
		else if Disc3 ends with "%" then delete "%" from Disc3
			else if Disc3 begins with "$" then delete "$" from Disc3
		Log Disc3 &":is Disc 3"
		
		set CstmChg to ReadText (((695,y),(765,y+18)))
		if CstmChg is empty then put 0 into CstmChg
		else if CstmChg ends with "%" then delete "%" from CstmChg
		put ManipulatePriceFormat(CstmChg) into CstmChg
		
		set NetPrice to ReadText(((782,y),(870,y+18)))
		put ManipulatePriceFormat(NetPrice) into NetPrice
		set Extended to ReadText (((875,y),(960,y+18)))
		put ManipulatePriceFormat(Extended) into Extended
		else
		Log "No Item Shipped"
		Exit handler
	end if
	
	Put ReadValueByY("Net Order Total",264)into NetOrderTotal
	Set NetOrderTotal to  ManipulatePriceFormat(NetOrderTotal)
	
	if ImageFound(2,text:"Shipping & Handling Total")
		Put ReadValueByY("Shipping & Handling Total",302) into ShipCharge
		Set ShipCharge to  ManipulatePriceFormat(ShipCharge)
	else 
		if ImageFound(2,text:"Handling Fee")
			Put ReadValueByY("Handling Fee",302) into ShipCharge
			Set ShipCharge to  ManipulatePriceFormat(ShipCharge)
		else 
			set ShipCharge to ""
			Log "Shippment Handling Charge Not Displayed !"
		end if
	end if
	
	if imageFound(5,text:"Total Invoice") 
		Put ReadValueByY("Total Invoice",256) into TotlInvoiceCost
	else 
		if imageFound(5,text:"CREDIT")
			put ReadValueByY("CREDIT",245) into TotlInvoiceCost
		end if
	end if
	
	Set  TotlInvoiceCost to  ManipulatePriceFormat( TotlInvoiceCost)
	
	return (InvoiceNoPDF, InvoiceDatePDF,OrderNoPDF, WhsPDF,deliveryNumber,customersPO, AccountNo,ItemCode, ItemDscrptn, ShipdQty, UM, UnitPrice, Disc1, Disc2, Disc3, CstmChg, NetPrice, Extended,TotlShpdQty,NetOrderTotal,ShipCharge,TotlInvoiceCost)
	
	end ReadMVdata
	
	
	
to ReadAddressDetails txt
	put ImageLocation(Text:txt) into Loc
	set Party to ReadText(Loc +(0,21))
	Log Party &" : is " &txt &" Party"
	set AdrsLine1 to ReadText(Loc +(0,37))
	set AdrsLine2 to ReadText(Loc +(0,53))
	set AdrsLine3 to ReadText(Loc +(0,69))
	Log AdrsLine1 &" : is " &txt &"Party Address Line1"
	Log AdrsLine2 &" : is " &txt &" Party Address Line2"
	Log AdrsLine3 &" : is " &txt &"Party Address Line3"
	Return (Party, AdrsLine1, AdrsLine2, AdrsLine3)	
end ReadAddressDetails


--Put ReadValueByX()into ()
to ReadValueByX txt,y
	put ImageLocation(Text: txt) into Loc
	set Val to ReadText(Loc +(0,y)) 
	Log val &" : is " &txt
	return Val
end ReadValueByX


--Put ReadValueByY()into ()
to ReadValueByY txt,x
	put ImageLocation(Text: txt) into Loc
	set Val to ReadText(Loc +(x,0))
	Log val &" : is " &txt
	return Val
end ReadValueByY

(*ReadSingleLineItemDetails*)

// This reads only Single Line Item only Based on "Total Shipped Quantity" field. 
to ReadSingleLineItemDetails
	Put ImageLocation(Text: "Total Shipped Qty.") into Loc
	set TotlShpdQty to ReadText(Loc+(220,3))
	set Item to ReadText(Loc-(0,28))
	Log Item
	if Item contains "$" or if Item contains "S&H Chg"
		Log Item &" : Found at Item Level"
		put Loc-(0,17) into Loc
	end if
	set ItemDscrptn to ReadText(Loc -(0,33))
	set ItemCode to ReadText(Loc- (0,56))
	put  Loc - (20,60) into ItemLineLoc
	Log ItemLineLoc
	set ShipdQty to ReadText(ItemLineLoc+(220,0))
	set UM to ReadText(ItemLineLoc+(282,0))
	set UnitPrice to ReadText(ItemLineLoc+ (377,0))
	set Disc1 to ReadText (ItemLineLoc+(435,0))
	set Disc2 to ReadText(ItemLineLoc+(506,0))
	set Disc3 to ReadText(ItemLineLoc+(566,0))
	set CstmChg to ReadText(ItemLineLoc+(629,0))
	set NetPrice to ReadText(ItemLineLoc+(730,0))
	set Extended to ReadText(ItemLineLoc+(836,0))
	Return(ItemCode, ItemDscrptn, ShipdQty, UM, UnitPrice, Disc1, Disc2, Disc3, CstmChg, NetPrice, Extended)
end ReadSingleLineItemDetails



to compare type, MV, Database
	if MV is in Database then
		logsuccess type && "matched!" && MV && "=" && Database
	else
		logerror type && "don't match!" && MV && "!=" && Database
	end if
end compare

to ManipulatePriceFormat Price
	log "Price Before Manipulation: " &Price
	if Price begins with "$" or if Price begins with "S" then delete the first character of Price
	put split (Price, ".") into Price1
	put  items 1  of Price1 into Whole
	put  items 2  of Price1 into Fraction
	if Whole contains "," then delete "," from whole
	if Fraction contains "00"
		put whole into Price
	else 
		if Fraction ends with "0"
			delete"0"from Fraction	
			put whole&"."&Fraction into Price
		end if
	end if
	Log "Manipulated Price: " &Price
	Return Price
end ManipulatePriceFormat


to ManipulateItemDescription
	if descp contains "Black"then replace"Black"with"blk"in descp
	if descp contains "white"then replace "White"with"wht"in descp
	if descp contains "Custom"then replace "Custom"with"CSTM"in descp
	if descp contains "Stand Bag"then replace "Stand Bag"with"SB"in descp
	if descp contains "Assorted"then replace "Assorted"with"Asst."in descp
end ManipulateItemDescription



to DateManipulate Date
	Log Date
	put split (Date, "/") into date1
	put  items 1  of date1 into Month
	put  items 2  of date1 into Day
	put  items 3  of date1 into Year
	put "20"&Year &Month&Day  into Date
	Log Date &" : After Manipulation"
	Return Date
end DateManipulate




