Log "Read from Invoice with MetaViewer"
"Other/MetaViewer".openMV
"Other/MetaViewer".loginMV "ajenkins", "ajenkins"
"Other/MetaViewer".lookupMV "904492748"
put "Other/MetaViewer".validateInvoice() into test
log test
"Other/MetaViewer".closeMV






--                                                   -x-x-xx-x-x-xx-xx-x
--   Sandbox
-- to workaround before making any changes to the existing function or script
--****************************************************************************

Log "Read from Invoice with MetaViewer"
"Other/MetaViewer".openMV
"Other/MetaViewer".loginMV "ajenkins", "ajenkins"
"Other/MetaViewer".lookupMV "904492748"
put ReadfromPDF() into Test
Log Test

to ReadfromPDF -- update to  "Other/MetaViewer".validateInvoice    #Function
	click "MetaViewer/PDF/MVFullscreen"
	Wait 5
	WaitFor 45,"MetaViewer/PDF/Titleist"
	
	put "MetaViewer/PDF/" into path
	
	set InvoiceNoPDF to ReadText((86,314))
	Log (InvoiceNoPDF  & " is the Invoice Number")
	
	set OrderNoPDF to ReadText((90,343))
	Log (OrderNoPDF  & " is the Order Number")
	
	set WhsPDF to ReadText((173,343))
	if WhsPDF is "06Y" then set WhsPDF to "060"
	if WhsPDF is "06B" then set WhsPDF to "061"
	Log WhsPDF && "is the warehouse number"
	
	set deliveryNumber to ReadText((250,343))
	Log deliveryNumber && "is delivery number"
	
	set customersPO to ReadText((437,345))
	Log customersPO && "is Customers PO"
	
	set AccountNoPayPDF to ReadText((745,342))
	Log (AccountNoPayPDF & " is the Account No of the Pay Account")
	
	set AccountNoShipPDF to ReadText((900,343))
	Log (AccountNoShipPDF & " is the Account No of the Ship Account")
	
	## Adding below to the existring validations
	
	
	(*
	set ShipToPartyAddress1 to readText((618,399)) -- DeliveryAddress in M3 Line 1
	set ShipToPartyAddress2 to readText((612,433)) --DeliveryAddress in M3 Line 2
	Log "Delivery Address in MV :- " &ShipToPartyAddress1
	Log ShipToPartyAddress2
	
	set PaymentDiscount to readText((532,539))
	Log "Payment Discoun in MV :- " &PaymentDiscount
	
	set PaymentTerms to readText((555,505))
	Log "Payment Terms in MV :- " &PaymentTerms
	*)
	
	put ImageLocation(Text:"Sold To") into Loc
	set SoldToParty to ReadText(Loc +(0,21))
	Log SoldToParty & "is Sold To Party"
	set SoldToAdrsLine1 to ReadText(Loc +(0,37))
	set SoldToAdrsLine2 to ReadText(Loc +(0,53))
	set SoldToAdrsLine3 to ReadText(Loc +(0,69))
	Log SoldToAdrsLine1 & " : is  Sold To Party Address Line1"
	Log SoldToAdrsLine2 & " : is  Sold To Party Address Line2"
	Log SoldToAdrsLine3 & " : is  Sold To Party Address Line3"
	
	## to scroll page down -------  ******second half of PDF, Y cordinates changes ********
	Click(700,140)
	ScrollWheelDown 10
	
	Set NetOrderTotal to readText((926,488)) 
	Log "Net Order Total :- " &NetOrderTotal
	
	
	return (InvoiceNoPDF, OrderNoPDF, WhsPDF, AccountNoPayPDF, AccountNoShipPDF, customersPO, deliveryNumber, ShipToPartyAddress1, ShipToPartyAddress2, PaymentDiscount, PaymentTerms)
end ReadfromPDF


---------------------------------------------------------------------

Put ReadAddressDetails ("Ship To") into (ShipToParty, ShipToPartyAddress1, ShipToPartyAddress2, ShipToPartyAddress3)
Put ReadAddressDetails ("Sold To") into(SoldToParty, SoldToAdrsLine1, SoldToAdrsLine2, SoldToAdrsLine3)
put ReadValueByX("Payment Terms",15) into(PaymentTerms)
put ReadValueByX("Payment Discount",15) into(PaymentDiscount)
put ReadValueByX("Delivery Method",15) into(DelMethd)
Put ReadValueByX("Due Date",15)into (DueDate)
to ReadAddressDetails txt
	put ImageLocation(Text: txt) into Loc
	set Party to ReadText(Loc +(0,21))
	Log Party &" : is " &txt &" Party"
	set AdrsLine1 to ReadText(Loc +(0,37))
	set AdrsLine2 to ReadText(Loc +(0,53))
	set AdrsLine3 to ReadText(Loc +(0,69))
	Log AdrsLine1 &" : is " &txt &"Party Address Line1"
	Log AdrsLine2 &" : is " &txt &" Party Address Line2"
	Log AdrsLine3 &" : is " &txt &"Party Address Line3"
	Return (Party, AdrsLine1, AdrsLine2, AdrsLine3)	
end ReadAddressDetails


to ReadValueByX txt,y
	put ImageLocation(Text: txt) into Loc
	set Val to ReadText(Loc +(0,y))
	Log val &" : is " &txt
	return Val
end readPaymentDetails


to ReadValueByY txt,x
	put ImageLocation(Text: txt) into Loc
	set Val to ReadText(Loc +(x,0))
	Log val &" : is " &txt
	return Val
end readPaymentDetails




