to login username, password
	Log "Logging in"
	teardown
	"M3/Application".open
	"M3/Login".login username, password
end login

to teardown
	wait 5
	repeat forever
		try 
			if ImageFound("M3/Application/ClosePanel") then
				Click "M3/Application/ClosePanel"
				throw "Not finished","closed panel"
			end if
			if ImageFound("M3/Application/ExitAGSButton") then 
				Click "M3/Application/ExitAGSButton"
				throw "Not finished","closed AGS"
			end if
			if ImageFound("M3/Application/OKErrorButton") then 
				Click "M3/Application/OKErrorButton"
				throw "Not finished","closed error pop up"
			end if
			exit repeat
		catch anException
			MoveTo ((0,0))
			wait 3
		end try
	end repeat
end teardown

to exitApp
	Log "Exit AGS"
	"M3/Application".close
end exitApp