to enterNewOrder customerNumber, coType, PO, priority, salesHold
	Log "Enter new order"
	"M3/OIS300".open
	"M3/OIS300".startNewOrder
	Wait while ImageFound("M3/OIS300/CustomerNumberField/CustomerNumberField")
	"M3/OIS300".enterCustomerNumber customerNumber, coType, salesHold
	//"M3/OIS300".submitOIS100A  (**Commented as it should not be at this postion in this flow*)
	"M3/OIS300".enterCustomersPO PO
	"M3/OIS300".submitOIS100G
	"M3/OIS300".acceptPOWarning
	"M3/OIS300".submitOIS100F
	"M3/OIS300".submitOIS100H
	"M3/OIS300".submitOIS100E priority
	"M3/OIS300".submitOIS102H
end enterNewOrder

to GenericOrderEntry customerNumber, coType, PO, TagField, DeliveryTerm, DeliveryMethod, TranctionResonCode, SalesHold, priority //BlanketAgreement
	Log "Enter new order"
	"M3/OIS300".open
	"M3/OIS300".zoom75prcnt
	"M3/OIS300".startNewOrder
	//if ImageFound(120,"M3/OIS300/CustomerNumberField/CustomerNumberField") then
	"M3/OIS300".enterCustomerNumber customerNumber, coType, SalesHold	
	//else
	//LogError "New Order not started" 
	//end if	
	"M3/OIS300".enterCustomersPO PO
	"M3/OIS300".submitOIS100A
	"M3/OIS300".acceptPOWarning
	"M3/OIS300".TagField TagField
	If DeliveryTerm <> "" then
		"M3/OIS300".DeliveryTerm DeliveryTerm
	End If
	If DeliveryMethod <> "" then
		"M3/OIS300".DeliveryMethod DeliveryMethod
	End if
	"M3/OIS300".submitOIS100G
	"M3/OIS300".submitOIS100V
	"M3/OIS300".acceptPOWarning
	"M3/OIS300".submitOIS100F
	"M3/OIS300".submitOIS100E  priority
	"M3/OIS300".submitOIS100H
	"M3/OIS300".submitOIS102H
	"M3/OIS101".EnterTransResonCode TranctionResonCode
	//"M3/OIS101".BlanketAgreement BlanketAgreement
end GenericOrderEntry

to recordCONumber
	Log "Enter order line"
	put "M3/OIS101".recordCONumber() into coNumber
	//"M3/OIS101".storeCONum
	Log coNumber
	return coNumber
end recordCONumber

to enterProduct itemCode,ConfigurationNo
	WaitFor 20, Image:"M3/OIS101/OIS101B1Title"
	"M3/OIS101".enterItemCode itemCode	
	"M3/OIS101".enterItemColor
	if ConfigurationNo="ConfigA1" then
		"M3/Configurations".ConfigA1
	else if  ConfigurationNo="ConfigA2" then
		"M3/Configurations".ConfigA2
	else if  ConfigurationNo="ConfigA3" then
		"M3/Configurations".ConfigA3
	else if  ConfigurationNo="ConfigA4" then
		"M3/Configurations".ConfigA4
	else if ConfigurationNo="ConfigB1" then
		"M3/Configurations".ConfigB1
	else if  ConfigurationNo="ConfigB2" then
		"M3/Configurations".ConfigB2
	else if  ConfigurationNo="ConfigB3" then
		"M3/Configurations".ConfigB3
	else if  ConfigurationNo="ConfigB4" then
		"M3/Configurations".ConfigB4
	else if ConfigurationNo="ConfigB5" then
		"M3/Configurations".ConfigB5
	else if ConfigurationNo="ConfigB6" then
		"M3/Configurations".ConfigB6
		//else if ItemCode = "TB7SX6CC" or if itemCode = "TB7SX14CC" or if itemCode ="TB7SX6TC" then 
		(*"M3/OIS101".enterItemQuantity productQuantity*)
		//"M3/Configurations".config001
		//	else
		//"M3/OIS101".configuratorA
	end if
	"M3/OIS101".closeFromOrderLines
end enterProduct

To EnterItemProductQuanConfig itemCode, quantity, ConfigurationNo
	"M3/OIS101".enterItemCode itemCode
	"M3/OIS101".enterItemQuantity quantity
	"M3/OIS300".ClickNextButton
	wait 5
	if ConfigurationNo="ConfigD1" then
		"M3/Configurations".ConFigD1
	else if  ConfigurationNo="ConfigD2" then
	"M3/Configurations".ConFigD2
	else if  ConfigurationNo="ConfigD3" then
	"M3/Configurations".ConFigD3
	else if  ConfigurationNo="ConfigD4" then
	"M3/Configurations".ConFigD4
	else if  ConfigurationNo="ConfigD5" then
	"M3/Configurations".ConFigD5
	else if  ConfigurationNo="ConfigD6" then
	"M3/Configurations".ConFigD6
	else if  ConfigurationNo="ConfigI1" then
	"M3/Configurations".ConFigI1
	else if  ConfigurationNo="Config W1" then
	"M3/Configurations".ConFigW1
	else if  ConfigurationNo="ConfigP1" then
	"M3/Configurations".ConFigP1
	else
	LogError "There is no Cofiguration Present"
	
End If
wait 5

End EnterItemProductQuanConfig

To GetLineStatus
	Click "M3/OIS101/selectline"
	Click "M3/OIS101/LineSlat"
	put  ImageLocation ("M3/OIS101/LineSlat") into loc
	Put loc+(-10,-5) into L1
	Put loc+(55,10) into L2
	put  ReadText((L1), (L2)) into LineStatus
	
	Log LineStatus
	If LineStatus<> "" then
		LogSuccess "Line Item Has Created With Line Status as:  "&"  "& LineStatus
		Return LineStatus
	Else
		LogError "Line Item has Not Created"
		
	End If
	
End GetLineStatus


to enterProductAndQuantity itemCode, quantity
	"M3/OIS101".enterItemCode itemCode
	"M3/OIS101".enterItemQuantity quantity
	"M3/Configurations".config002
	"M3/OIS101".closeFromOrderLines
end enterProductAndQuantity

to EnterProductWithPromo itemCode, quantity, PromoCod, WHNumber
	if PromoCod <>"" then
		"M3/OIS101".setPromocode
		"M3/OIS101".EnterPromoCode PromoCod
	End if
	if WHNumber <> "" then
		"M3/OIS101". enterWhearhouseNumb WHNumber
	End if
	"M3/OIS101".enterItemCode itemCode
	"M3/OIS101".enterItemQuantity quantity
	click "M3/OIS101/Next"
	wait 2
END EnterProductWithPromo

to GetPromoCodevalue PromoCod
	if PromoCod <>"" then
		"M3/OIS101".ChangeViewInOis101
		"M3/OIS101".getPromocodevalue
	End if
end GetPromoCodevalue

To ApplyBlanketAgreement BlanketAgreement
	If BlanketAgreement <> "" then
		"M3/OIS101".BlanketAgreement BlanketAgreement
	End If
End ApplyBlanketAgreement

(*To GenricRowNcolumn IndexColItem, IndexColQuan,IndexColPromo, indexRow
	set ExcelFile to workbook(ResourcePath("6-GenericStockOrder.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	Put Cell(worksheet, "&IndexColItem& &indexRow) into itemCodeGen
	Put Cell(worksheet, ndexColQuan&indexRow) into quantityGen
	Put Cell(worksheet, IndexColPromo&indexRow) into PromoCodGen
	
End GenricRowNcolumn

To AddLineItem itemCodeGen, quantityGen, PromocodGen
	set itemCodeGen to itemCode
	set quantityGen to quantity
	set PromoCodGen to PromoCod
	
	//"M3/OIS101".setPromocode
	"M3/OIS101".enterItemCode itemCode
	"M3/OIS101".enterItemQuantity quantity
	if PromoCod <>"" then
		"M3/OIS101".EnterPromoCode PromoCod
	End if
	
	click "M3/OIS101/Next"
	wait 2
	"M3/OIS101".ChangeViewInOis101
	///"M3/OIS101".getPromocodevalue
	Click "M3/OIS101/ADDButton"
End AddLineItem*)

//                                                                             *****
(*>>>>>>>>>Creates New order with or without delivery Terms and Method based on the data >>>>>>> *)
to CreateNewOrder customerNumber, coType, PO, TagField, DeliveryTerm, DeliveryMethod, TranctionResonCode, BlanketAgreement, Priority
	if DeliveryTerm <> "" and  DeliveryMethod <> ""
		"Flows/OrderEntry".GenericOrderEntry customerNumber, coType, PO, TagField, DeliveryTerm, DeliveryMethod, TranctionResonCode, BlanketAgreement
	else 
		"Flows/OrderEntry".enterNewOrder customerNumber, coType, PO, Priority
	end if
end CreateNewOrder
