to doScheduling coNumber
	Log "Do scheduling"
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNumber)
	put "M3/PMS170".createScheduleNumber() into scheduleNumber
	"M3/PMS170".scheduleNew scheduleNumber
	"M3/PMS170".releaseMO
	"M3/PMS170".close
	"M3/PMS100".open
	"M3/PMS100".lookupSchedule scheduleNumber
	"M3/PMS100".printShopTraveler scheduleNumber
end doScheduling

to doStatusScheduling coNumber, product
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNumber)
	if ImageFound("M3/PMS170/Product_OrderLine") then
		Log "search the product"
		"M3/PMS170".select_Product product
	else
		throw "Error","Product field is not Appears"
	end if
	"M3/PMS170".change_line_status
	if Imagefound("M3/PMS170/Related") then
		
		// As per the Script ZCutomization the schedule number should stars with "300".
		set ExcelFile to workbook(ResourcePath("ZCustomaization.xlsx"))
		set worksheet1 to Excelfile.Worksheet("Sheet2")
		put Cell(worksheet1, B1) into count
		put count + 1 into count
		put count into Cell(worksheet1, "B1")
		log "Cell value: " & Cell(worksheet1, B1)
		put 30025092017+(100000000*count) into scheduleNumber
		set scheduleNumber to scheduleNumber
		log "New schedule number: " & scheduleNumber
		
		"M3/PMS170".create_schedule_number scheduleNumber
	else
		throw "Error","Schedulenumber is not created"
		
	end if
	"M3/PMS170".releaseMO
	"M3/PMS170".close
	"M3/MWS150".openMWS150
	"M3/MWS150".search_order_in_MWS150 coNumber
	"M3/MWS150".waitForRONum
	//"M3/MWS150".recordReqnumber
	put "M3/MWS150".recordReqnumber() into ReqNumber
	return ReqNumber
end doStatusScheduling