(* 
Name: US-Gear-06
Description: Enter a basic custom CC Players 5 stand bag ,one personalization, FXG Delivery Method / BPG Delivery Term should apply to validate $5 per bag shows on Invoice
Author: Andy Jenkins
 *)

Log "Intializing Excel data sheet for This Script"
// read user Name and Password for M3 Application from Login sheet of Datastore excel File
//run DataStore.ConfigValues UserName, Password, customerNumber, coType
set ExcelFile to workbook(ResourcePath("1-Datastore.xlsx"))
set worksheet to ExcelFile.Worksheet("Login")
Put Cell(worksheet,"A2") into username
Put Cell(worksheet,"B2") into password
Put Cell(worksheet,"C5") into customerNum
Put Cell(worksheet,"D2") into coType
Put Cell(worksheet,"E4") into PO
Put Cell(worksheet,"F5") into itemCode
Put Cell(worksheet,"G2") into productQuantity
Put Cell(worksheet,"H2") into DCAUser
Put Cell(worksheet,"I2") into DCAPswrd

"Flows/Application".login username, password

(************** Order entry ***************)
"Flows/OrderEntry".enterNewOrder customerNum, coType, PO
put "Flows/OrderEntry".recordCONumber() into coNum
"Flows/OrderEntry".enterProduct itemCode

(************** Scheduling ***************)
"Flows/Scheduling".doScheduling coNum
put "M3/PMS100".recordMO() into moNum

(************** Picking ******************)
"Flows/Picking".doPicking

(************** Manufacturing *************)
"Flows/ManufacturinPacking".doManufacturing moNum

(************** Packing ******************)
put "Flows/ManufacturingPacking".validatePacking(username,password,coNum) into delNum
"Flows/Other".recordRun coNum, moNum, schedNum, delNum

(************** Shipping *****************)
"Flows/Shipping".doShipping delNum
"Flows/Shipping".validateShipping coNum

(************** Exit *********************)
Log "Exit AGS"
"M3/Application".close






