(* 
Name: US-Gear-06
Description: Enter a basic custom CC Players 5 stand bag ,one personalization, FXG Delivery Method / BPG Delivery Term should apply to validate $5 per bag shows on Invoice
Author: Andy Jenkins
 *)

Log "Intializing Excel data sheet for This Script"
// read user Name and Password for M3 Application from Login sheet of Datastore excel File
//run DataStore.ConfigValues UserName, Password, customerNumber, coType
set ExcelFile to workbook(ResourcePath("1-Datastore.xlsx"))
set worksheet to ExcelFile.Worksheet("Login")
Put Cell(worksheet,"A2") into UserName
Put Cell(worksheet,"B2") into Password
Put Cell(worksheet,"C5") into customerNumber
Put Cell(worksheet,"D2") into coType
Put Cell(worksheet,"E4") into PO
Put Cell(worksheet,"F5") into itemCode
Put Cell(worksheet,"G2") into productQuantity
Put Cell(worksheet,"H2") into DCAUser
Put Cell(worksheet,"I2") into DCAPswrd

Log "Logging in"
"M3/Application".open
"M3/Login".login UserName, Password

"Flows/OrderEntry".enterNewOrder customerNumber, coType, PO

put "Flows/OrderEntry".recordCONumber() into coNumber

"Flows/OrderEntry".enterProduct itemCode

"M3/OIS101".closeFromOrderLines

(*******************************Begin Scheduling *****************)
Log "Do scheduling"
"M3/PMS170".open
"M3/PMS170".lookUp(coNumber)
put "M3/PMS170".createScheduleNumber() into scheduleNumber
"M3/PMS170".scheduleNew scheduleNumber
"M3/PMS170".releaseMO
"M3/PMS170".close
"M3/PMS100".open
"M3/PMS100".lookupSchedule scheduleNumber
"M3/PMS100".printShopTraveler scheduleNumber
put "M3/PMS100".recordMO() into moNumber
"M3/PMS100".pick
"M3/PMS100".close
Log "Exit AGS"
"M3/Application".close
(*******************************End Scheduling *****************)

throw "Unsupported", "environment does not currently support DCA"

(*******************************Begin Manufacturing *****************)
Log "Do manufacturing"
// Open DCA
"Other/DCA".open
"Other/DCA".manufacture moNumber
"Other/DCA".close
(***********************************End Manufacturing ***********)

"M3/Application".open
"M3/Login".login username, password
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
"M3/OIS300".openDeliveryToolbox
put "M3/OIS300".recordDeliveryNumber into deliveryNumber
"M3/OIS300".confirmStatusPacked
"M3/OIS300".closeFromDeliveryToolbox
Log "Exit AGS"
"M3/Application".close


Log "CO: " & coNumber
Log "MO: " & moNumber
Log "Schedule: " & scheduleNumber
Log "Delivery: " & deliveryNumber
DataStore.recordRun coNumber, moNumber, scheduleNumber, deliveryNumber

(***********************************Begin Shipping with Flagship *****************)
Log "Shipping with Flagship"
"Web/Flagship".open
"Web/Flagship".login
"Web/Flagship".ship deliveryNumber
"Web/Flagship".close
"M3/Application".open

"M3/Login".login "ajenkins", "Acushnet#1"
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
"M3/OIS300".openDeliveryToolbox
"M3/OIS300".confirmStatusShipped
"M3/OIS300".closeFromDeliveryToolbox

Log "Exit AGS"
"M3/Application".close
(***********************************End Shipping  *****************)

(*X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-XX-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X*)





