(* 
Name: Bulk MO
Description: 
Author: Ramya & Ofir
 *)

//define global variables
global username
global password

"Datastore".setLoginVariables 3

// log in to application
"Flows/Application".login username, password

Log "Logging in"
"M3/Application".open

repeat forever
	(*>>>>>>>>>>>Scheduling>>>>>>>>>>>>*)
	Log "Do scheduling"
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNum)
	put "M3/PMS170".createScheduleNumber() into scheduleNumber
	"M3/PMS170".scheduleNew scheduleNumber
	"M3/PMS170".releaseMO
	"M3/PMS170".close
	"M3/PMS100".open
	"M3/PMS100".lookupSchedule scheduleNumber
	"M3/PMS100".printShopTraveler scheduleNumber
	put "M3/PMS100".recordMO() into moNumber
	"M3/PMS100".pick
	"M3/PMS100".close
end repeat

//post DCA check packed status
(*"M3/Application".open
"M3/Login".login username, password
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
"M3/OIS300".openDeliveryToolbox
put "M3/OIS300".recordDeliveryNumber into deliveryNumber
"M3/OIS300".confirmStatusPacked
"M3/OIS300".closeFromDeliveryToolbox

Log "Exit AGS"
"M3/Application".close

Log "CO: " & coNumber
Log "MO: " & moNumber
Log "Schedule: " & scheduleNumber
Log "Delivery: " & deliveryNumber
DataStore.recordRun coNumber, moNumber, scheduleNumber, deliveryNumber
*)

//////////////////////////////picking//////////////////////////////////////

(*Log "Do picking"
"M3/PMS100".open

WaitFor 20, "M3/PMS100/FacilityField"
Click "M3/PMS100/FacilityField"
TypeText controlKey, "a"
TypeText deleteKey
TypeText "061"
TypeText Return

"M3/PMS100".lookup_3 coNumber
"M3/PMS100".checkAllocationStatus
"M3/PMS100".openDeliveryToolbox
"M3/PMS100".checkDeliveryStatus
"M3/PMS100".checkPickingListsImage
Click "M3/PMS100/HPickingLists"
"M3/PMS100".checkPickingStatusImage*)





/////////////////////////////////////////flagship////////////////////////////
(*Log "Shipping with Flagship"
"Web/Flagship".open
"Web/Flagship".login
"Web/Flagship".ship deliveryNumber
"Web/Flagship".close
"M3/Application".open

"M3/Login".login "ajenkins", "Acushnet#1"
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
"M3/OIS300".openDeliveryToolbox
"M3/OIS300".confirmStatusShipped
"M3/OIS300".closeFromDeliveryToolbox

Log "Exit AGS"
"M3/Application".close*)
//////////////////////////////////////manufacturingin m3 with kpack////

//prerequisite:yet to be handled(CO comes back form order entry)

(*"M3/PMS100".open
"M3/PMS100".lookup_4 coNumber
"M3/PMS100".checkAllocationStatus


Log "Do Manufacturing in M3"
"M3/PMS070".lookupMOnumber


Click "M3/PMS070/operation0100"
TypeText controlKey, "a"
TypeText deleteKey

TypeText "0100"
TypeText Return

Click "M3/PMS070/Changeforoperation"

"M3/PMS070".compareOrderandManufQuantity

Click"M3/PMS070/Nextbutton"

// capture step for remains and manufacturing qty validation
"M3/PMS070". compareRemainsandManufQuantity
click "M3/PMS070/close"

"M3/PMS100".open
click "M3/PMS070/refresh"
"M3/PMS070".checkMOStatus
click "M3/PMS070/close100"

"M3/PMS070".lookupMOnumber

Click "M3/PMS070/operation8000"

TypeText controlKey, "a"
TypeText deleteKey

TypeText "8000"
TypeText Return
Click "M3/PMS070/Changeforoperation"
"M3/PMS070".compareOrderandManufQuantity
Click"M3/PMS070/Nextbutton"
// skipped steps related to Man compl flag and location values, as unable to find the fields

"M3/PMS070". compareRemainsandManufQuantity
click "M3/PMS070/close"
click "M3/PMS070/close"


click "M3/PMS070/BacktoPMS100"
click "M3/PMS070/RefreshPMS100"
"M3/PMS070".checkMOStatus
"M3/PMS070".compareOrderandManufQuantity

/// packing with kpack////
"Web/KPack".OpenKpackUSVista
"Web/KPack".LoginToKpackUSVista
click "M3/KPack/OrderNum"
TypeText controlKey, "a"
TypeText deleteKey

TypeText "0013139821001"

Click "M3/KPack/LoadOrderutton"
Click "M3/KPack/ProductID"
Click "M3/KPack/FastPackDeselected"
Click "M3/KPack/Autopackselect"
Click "M3/KPack/Packbutton"
Click "M3/KPack/SelectBoxType"
Click "M3/KPack/SelectBoxtypedropdown"
Click "M3/KPack/Containercomplete"
"Web/KPack".compareOrderandPackedQuantity
Click "M3/KPack/OrderComplete"*)

to generateMOCO
	//log in to AGS
	Log "Logging in"
	"M3/Application".open
	
	//read in necessary data
	set ExcelFile to workbook(ResourcePath("2-Datastore.xlsx"))
	set worksheet to ExcelFile.Worksheet("Login")
	Put Cell(worksheet,"A3") into UserName
	Put Cell(worksheet,"B3") into Password
	Put Cell(worksheet,"C2") into customerNumber
	Put Cell(worksheet,"D2") into coType
	Put Cell(worksheet,"E2") into PO
	
	(*>>>>>>>>Start Order Entry>>>>>>>>>>>>>*)
	"M3/Login".login UserName, Password
	
	"Flows/OrderEntry".enterNewOrder customerNumber, coType, PO
	
	put "Flows/OrderEntry".recordCONumber() into coNum
	
	"Flows/OrderEntry".enterProductAndQuantity "TA5TVBPC", "1"
	
	"M3/OIS101".closeFromOrderLines
	
	Log coNum
	
	Log "Exit AGS"
	"M3/Application".close
	
	//don't continue running the script
	throw "Finished!", "some comment"
end generateMOCO

to doOrderEntryThroughPicking
	//read in necessary data
	set ExcelFile to workbook(ResourcePath("2-Datastore.xlsx"))
	set worksheet to ExcelFile.Worksheet("Login")
	Put Cell(worksheet,"A3") into UserName
	Put Cell(worksheet,"B3") into Password
	Put Cell(worksheet,"C2") into customerNumber
	Put Cell(worksheet,"D2") into coType
	Put Cell(worksheet,"E2") into PO
	
	(*>>>>>>>>Start Order Entry>>>>>>>>>>>>>*)
	"M3/Application".open
	
	"M3/Login".login UserName, Password
	
	"Flows/OrderEntry".enterNewOrder customerNumber, coType, PO
	
	put "Flows/OrderEntry".recordCONumber() into coNum
	
	"Flows/OrderEntry".enterProductAndQuantity "TA5TVBPC", "1"
	
	"M3/OIS101".closeFromOrderLines
	
	(*>>>>>>>>>>>Scheduling>>>>>>>>>>>>*)
	Log "Do scheduling"
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNum)
	put "M3/PMS170".createScheduleNumber() into scheduleNumber
	"M3/PMS170".scheduleNew scheduleNumber
	"M3/PMS170".releaseMO
	"M3/PMS170".close
	"M3/PMS100".open
	"M3/PMS100".lookupSchedule scheduleNumber
	"M3/PMS100".printShopTraveler scheduleNumber
	put "M3/PMS100".recordMO() into moNumber
	"M3/PMS100".pick
	"M3/PMS100".close
end doOrderEntryThroughPicking






















