(* 
Name: US-Gear-06
Description: Enter a basic custom CC Players 5 stand bag ,one personalization, FXG Delivery Method / BPG Delivery Term should apply to validate $5 per bg shows on Invoice
Author: Andy Jenkins 
testing
 *)

Log "Logging in"
"M3/Application".open
"M3/Login".login "AGSAutoT03", "SERVICE$08"


Log "Enter new order"
"M3/OIS300".open
"M3/OIS300".startNewOrder
"M3/OIS300".enterCustomerNumber "US00031762", "USA"
"M3/OIS300".submitOIS100A
"M3/OIS300".enterCustomersPO "US-Gear-33"
"M3/OIS300".submitOIS100G
"M3/OIS300".acceptPOWarning
"M3/OIS300".submitOIS100F
"M3/OIS300".submitOIS100H
"M3/OIS300".submitOIS100E
"M3/OIS300".submitOIS102H

Log "Enter order line"
put "M3/OIS101".recordCONumber() into coNumber
Log coNumber
"M3/OIS101".enterItemCode("TA5TVBPC")
"M3/OIS101".enterItemQuantity "1"
"M3/Configurations".config002
(*"M3/OIS101".enterItemColor
"M3/OIS101".configuratorA*)
"M3/OIS101".closeFromOrderLines

Log "Do scheduling"
"M3/PMS170".open
"M3/PMS170".lookUp(coNumber)
put "M3/PMS170".createScheduleNumber() into scheduleNumber
"M3/PMS170".scheduleNew scheduleNumber
"M3/PMS170".releaseMO
"M3/PMS170".close
"M3/PMS100".open
"M3/PMS100".lookupSchedule scheduleNumber
"M3/PMS100".printShopTraveler scheduleNumber
put "M3/PMS100".recordMO() into moNumber
"M3/PMS100".pick
"M3/PMS100".close

//M3 manufacturing with PMS070
"M3/PMS070".open
"M3/PMS070".lookupMO moNumber

