(*ZC Customization Process*)

set ExcelFile to workbook(ResourcePath("ZCustomaization.xlsx"))
set worksheet to ExcelFile.Worksheet("Sheet1")
Put Cell(worksheet,A2) into username 
Put Cell(worksheet,B2) into password 
Put Cell(worksheet,A6) into coNumber 
Put Cell(worksheet,D6) into product
Put Cell(worksheet,E6) into Status_Line
Put Cell(worksheet,E6) into sh_prifx
Put Cell(worksheet,G6) into sh_sufix



Log "Logging in"
"M3/Application".open
"M3/Login".login username, password
waitfor 10, "M3/Login/itLogoff"
If ImageFound( "M3/Login/itLogoff") then
	LogSuccess "User Successfully Loggedin"
else
	LogError "User Unable login"
	
End If
If ImageFound( "M3/Login/itLogoff") then
	Log "Open PMS170 Tcode"
	waitfor 10, "M3/Login/itLogoff"
	"M3/PMS170".open
	"M3/PMS170".lookUp_2(coNumber)
end if
if ImageFound("M3/PMS170/OrderLine/Product_OrderLine") then
	Log "search the product"
	"M3/PMS170".select_Product product
else
	Logerror "Product field is not Appears"
end if
"M3/PMS170".change_line_status Status_Line
if Imagefound("M3/PMS170/Related") then
	
	"M3/PMS170".creatinguniqueScheduleNumber
	"M3/PMS170".create_schedule_number scheduleNumber
else
	Logerror "Schedulenumber is not created"
	
end if
"M3/PMS170".releaseMO
"M3/PMS170".close
"M3/MWS150".openWMS150
"M3/MWS150".search_order_in_MWS150 coNumber
"M3/MWS150".recordReqnumber
"M3/MWS150".closeMWS150
"M3/MMS100".openMMS100
"M3/MMS100".searchReqnumber ReqNumber
"M3/MMS100".DeliveryToolBox
"M3/MMS100".MPacking
"M3/MWS150".openWMS150
"M3/MWS150".search_order_in_MWS150 coNumber
"M3/MWS150".ReqOrderStatus
"M3/MWS150".RecordPoNumber
"Web/KPack".OpenKpack
"Web/KPack".LoginToKpackZC10041
