(* 
Name: Automatic PO receiving
Description: Read input from Cognos Report 
Author: Ramya
 *)


// fetching username,password and po number from excelfile
set ExcelFile to workbook(ResourcePath("AutomaticPOReceiving.xlsx")) 
set worksheet to ExcelFile.Worksheet("Sheet1")
set worksheet2 to ExcelFile.Worksheet("Sheet2")
Put Cell(worksheet,A2) into username
Put Cell(worksheet,B2)into password
Put Cell(worksheet2,K2) into poNumber

Log "Logging in"
"M3/Application".open
"M3/Login".login username, password
"M3/PPS300".openpoNumber
"M3/PPS300".poReceipt poNumber
"M3/PPS300".delynoteno poNumber
click "M3/PPS300/Next"

typetext controlkey, ("M3/PPS300/received qty,5")
click "M3/PPS300/Actions"
click  "M3/PPS300/XClose"


"M3/PPS310".open
"M3/PPS310".poReceipt
click "M3/PPS300/Receivingnum"
TypeText  controlkey, "a"
TypeText deleteKey
Typetext "14001"

click "M3/PPS300/PPS310/NextPPS310"

click  "M3/PPS300/ConfirmUpdateF14"








