(* 
Name: US-Gear-90-A
Description: Records the PO number and completes PO receipt portion of the test
Author: Andy jenkins
 *)

"M3/Application".open
"M3/Login".login "ajenkins", "Acushnet#1"
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
put "M3/OIS101".recordPONumber into poNumber
"M3/OIS101".closeFromOrderLines

Log "Enter PO Receipt"
"M3/PPS300".open
"M3/PPS300".poReceipt poNumber
"M3/PPS300".close

Log "Check PO Status"
"M3/OIS300".open
"M3/OIS300".lookupCO coNumber
"M3/OIS300".enterOrderLines
"M3/OIS101".supplyChain
"M3/OIS300".confirmStatusPutAway
"M3/OIS300".closeFromOrderLines

Log "Exit AGS"
"M3/Application".close