(*ZC Customization Process*)

set ExcelFile to workbook(ResourcePath("ZCustomaization.xlsx"))
set worksheet to ExcelFile.Worksheet("Sheet1")
set worksheet1 to Excelfile.Worksheet("Sheet2")
Put Cell(worksheet,A2) into username 
Put Cell(worksheet,B2) into password 
Put Cell(worksheet,A7) into coNumber 
Put Cell(worksheet,B7) into product
Put Cell(worksheet,C6) into Status_Line
Put Cell(worksheet1,B1) into count


Log "Logging in"
"M3/Application".open
"M3/Login".login username, password
waitfor 10, "M3/Login/itLogoff"
If ImageFound( "M3/Login/itLogoff") then
	LogSuccess "User Successfully Loggedin"
else
	LogError "User Unable login"
	
End If
If ImageFound( "M3/Login/itLogoff") then
	Log "Open PMS170 Tcode"
	waitfor 10, "M3/Login/itLogoff"
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNumber)
end if
if ImageFound("M3/PMS170/Product_OrderLine") then
	Log "search the product"
	"M3/PMS170".select_Product product
else
	Logerror "Product field is not Appears"
end if
"M3/PMS170".change_line_status Status_Line
if Imagefound("M3/PMS170/Related") then
	
	// As per the Script ZCutomization the schedule number stars with 300
	
	put Cell(worksheet1, B1) into count
	put count + 1 into count
	put count into Cell(worksheet1, "B1")
	log "Cell value: " & Cell(worksheet1, B1)
	put 30025092017+(100000000*count) into scheduleNumber
	set scheduleNumber to scheduleNumber
	log "New schedule number: " & scheduleNumber
	
	"M3/PMS170".create_schedule_number scheduleNumber
else
	Logerror "Schedulenumber is not created"
	
end if
"M3/PMS170".releaseMO
"M3/PMS170".close
"M3/MWS150".openMWS150
"M3/MWS150".search_order_in_MWS150 coNumber
"M3/MWS150".recordReqnumber
"M3/MWS150".closeMWS150
"M3/MMS100".openMMS100
"M3/MMS100".searchReqnumber ReqNumber
"M3/MMS100".DeliveryToolBox
"M3/MMS100".MPacking
"M3/MWS150".openWMS150
"M3/MWS150".search_order_in_MWS150 coNumber
"M3/MWS150".ReqOrderStatus
"M3/MWS150".RecordPoNumber
"Web/KPack".OpenKpack
"Web/KPack".LoginToKpackZC10041














