(* 
Name: Bulk MO
Description: 
Author: Ramya & Ofir
*)

// declare login variables
global username, password, coNum, prodNum


// initialize login variables
"Datastore".setLoginVariables 3

// initialize data line counter
put 4 into dataIndex

(************** Start Test ***************)
repeat forever
	
	(************** Set up data *************)
	//initialize data variables
	DataStore.setDataScript2 dataIndex
	
	//increment counter
	put dataIndex + 1 into dataIndex
	
	//break if no more data
	if coNum is empty then exit repeat
	
	//Log "CO# " & coNum
	
	(*>>>>>>>>>>>Scheduling>>>>>>>>>>>>*)
	// log in to application
	"Flows/Application".login username, password
	
	(*>>>>>>>>>>>Scheduling>>>>>>>>>>>>*)
	put "Flows/Scheduling".doScheduling(coNum) into schedNum
	put "M3/PMS100".recordMO() into moNum
	
	(************** Picking ******************)
	"M3/PMS100".pick
	"M3/PMS100".close
	
	(************** Manufacturing/Packing ******)
	Log "Do manufacturing"
	
	"Flows/ManufacturingPacking".doManufacturingM3 coNum, moNum
	(************** Packing ******************)
	// add KPack here by moving working code from function "doFullRun"
	"Flows/Application".exitApp
	
	"Flows/Other".recordRun coNum, moNum, schedNum, delNum
end repeat

to generateMOCO
	//log in to AGS
	Log "Logging in"
	"M3/Application".open
	
	// declare login variables
	global username, password
	
	// initialize login variables
	"Datastore".setLoginVariables 3
	
	"M3/Login".login username, password
	
	(*>>>>>>>>Start Order Entry>>>>>>>>>>>>>*)
	"Flows/OrderEntry".enterNewOrder "US00025028", "USA", "Automation Script #2"
	put "Flows/OrderEntry".recordCONumber() into coNum
	"Flows/OrderEntry".enterProduct "TB7SX14CC", "ConfigB5"
	(*"Flows/OrderEntry".enterProductAndQuantity "TA5TVBPC", "1"*)
	
	Log "CONUM:" && coNum
	
	Log "Exit AGS"
	"M3/Application".close
	
	//don't continue running the script
	(*throw "Finished!", "some comment"*)
end generateMOCO

to doFullRun
	// declare login variables
	global username, password, prodNum
	// initialize login variables
	"Datastore".setLoginVariables 3
	"M3/Application".open
	"M3/Login".login username, password
	(*>>>>>>>>>>Order Entry>>>>>>>>>>>>>*)
	"Flows/OrderEntry".enterNewOrder "US00025028", "USA", "US-Gear-06"
	put "Flows/OrderEntry".recordCONumber() into coNum
	//"Flows/OrderEntry".enterProductAndQuantity "TA5TVBPC", "1"
	"Flows/OrderEntry".enterProduct "TB7SX14CC", "ConfigB5"
	(*>>>>>>>>>>>Scheduling>>>>>>>>>>>>*)
	put "Flows/Scheduling".doScheduling(coNum) into schedNum
	put "M3/PMS100".recordMO() into moNum
	(************** Picking ******************)
	"M3/PMS100".pick
	"M3/PMS100".close
	(************** Manufacturing/Packing ******)
	Log "Do manufacturing"
	"Flows/ManufacturingPacking".doManufacturingM3 coNum, moNum
	(************** Packing ******************)
	// add KPack here by moving working code from function "doFullRun"
	"Flows/Application".exitApp
	"Flows/Other".recordRun coNum, moNum, schedNum, delNum
end doFullRun

to isAccessory prodNum
	if the second character of prodNum is "A" then
		return TRUE
	end if
end isAccessory

to isBag prodNum
	if the second character of prodNum is "B" then
		return TRUE
	end if
end isAccessory