(*ZC Customization Process*)

// declare login variables
global username, password

// initialize login variables
"Datastore".setLoginVariables 4

global data

// initialize data line counter
put 2 into dataIndex

"Flows/Application".login username, password
(************** Start Test *********************)
repeat forever
	Datastore.setSimpleData "3-data.xlsx", "Sheet1", dataIndex
	//increment counter
	put dataIndex + 1 into dataIndex
	
	//break if no more data
	if data is empty then exit repeat
	Put data into coNumber
	Log "CO# " & coNumber
	"M3/PMS170".open
	"M3/PMS170".lookUp(coNumber)
	
	if "M3/RPS010".inventoryCheck() is "noStock" 
		Logerror "ATP Quqntity was less then the Required Quantity for the  CO# was:-  "&coNumber
		"M3/PMS170".close
		Next repeat
	else
		
		"M3/PMS170".close
		Put data into coNumber
		DoStatuScheduling coNumber
		
	End if
end repeat

(************** Exit ***************************)
"Flows/Application".exitApp
To DoStatuScheduling coNumber

	(************** Scheduling *********************)
	put "Flows/Scheduling".doStatusScheduling(coNumber) into reqNum
	
	(************** Picking, Packing, Shipping *********)
	put "Flows/Picking".doStatusPicking(reqNum,coNumber) into poNum
	
End DoStatuScheduling



to generateZCOrder
	// declare login variables
	global username, password
	
	// initialize login variables
	"Datastore".setLoginVariables 4
	
	(************** Start flow **********************)
	"Flows/Application".login username, password
	
	(************** Order entry *********************)
	"Flows/OrderEntry".enterNewOrder "US00002181", "USA", "06Y ZC", "7", ""
	put "Flows/OrderEntry".recordCONumber() into coNumber
	"Flows/OrderEntry".enterProductAndQuantity "TA5ACMFTWLC", "1"
	
	(************** Exit ***************************)
	"Flows/Application".exitApp
	Log coNumber
end generateZCOrder

to doFullRun
	// declare login variables
	global username, password
	
	// initialize login variables
	"Datastore".setLoginVariables 4
	
	(************** Start flow **********************)
	"Flows/Application".login username, password
	
	(************** Order entry *********************)
	"Flows/OrderEntry".enterNewOrder "US00002181", "USA", "06Y ZC", "7"
	put "Flows/OrderEntry".recordCONumber() into coNumber
	"Flows/OrderEntry".enterProductAndQuantity "TA5ACMFTWLC", "1"
	
	(************** Scheduling *********************)
	put "Flows/Scheduling".doStatusScheduling(coNumber,product) into ReqNumber
	
	(************** Picking, Packing, Shipping *********)
	put "Flows/Picking".doStatusPicking(ReqNumber,coNumber) into poNumber
	
	(************** Exit ***************************)
	"Flows/Application".exitApp
end doFullRun