to open
	DoubleClick "M3/Application/InforShortcut"
end open

to close
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click "M3/Application/ExitAGSButton"
	//Click "M3/Application/ExitConfirmationButton"
end close

To MaximizePanel
	if ImageFound (20,"M3/Application/ResizePanel") then
		Log "PMS170 found in Maximize state"
	else 
		if ImageFound (3,"M3/Application/MaximizePanel")
			Click "M3/Application/Maximize"
			Log "Panel PMS170 was resized to Maximize"
		end if
	end if
End MaximizePanel