to config001
	TypeText 1
	Click (238,228)
	(*Click (Image:"M3/Configurations/configuration001/BagColorBlack", WaitFor:10)*)
	Click "M3/Configurations/configuration001/NumCustomization"
	Click "M3/Configurations/configuration001/CustomizationLocation"
	Click (Image:"M3/Configurations/configuration001/Personalization1", WaitFor:10)
	Click "M3/Configurations/configuration001/PersonalizationText"
	TypeText Return
	TypeText "My automated personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/BlockLettering"
	Click "M3/Configurations/configuration001/VVhiteColor"
	Click "M3/Configurations/configuration001/NoOrderNotes"
	Click "M3/Configurations/configuration001/DoubleStrap"
	(*Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if
	Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if
	Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if*)
end config001

to config002
	Click (Image:"M3/Configurations/config2/ProofRequired", WaitFor:136)
	Click (Image:"M3/Configurations/config2/NumCustomizations", WaitFor:30)
	Click "M3/Configurations/config2/Personalization"
	Click "M3/Configurations/config2/Application1"
	Click (279,242)
	TypeText Return
	TypeText "Acushnet script 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/BlockLettering"
	Click "M3/Configurations/configuration001/VVhiteColor"
	Click "M3/Configurations/configuration001/NoOrderNotes"
end config002

to ConfigB1 // similar to B5
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/CustomizationLocation"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB1

to ConfigB2 // Similar to B5
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/CustomizationLocation"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB2

to ConfigB3 // similar to B5
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/CustomizationLocation"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB3

to ConfigB4 // similar to B5
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/CustomizationLocation"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB4

to ConfigB5
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/CustomizationLocation"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB5

to ConfigB6
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/LocationButtonSpineL1","M3/Configurations/configuration001/CustomizationLocation/LocationSpinePocketL1"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigB6

to ConfigA2
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/LocationButtonSpineL1","M3/Configurations/configuration001/CustomizationLocation/LocationSpinePocketL1"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigA2

