to config001
	TypeText 1
	Click (238,228)
	(*Click (Image:"M3/Configurations/configuration001/BagColorBlack", WaitFor:10)*)
	Click ("M3/Configurations/configuration001/NumCustomization", waitFor:10)
	Click "M3/Configurations/configuration001/CustomizationLocation"
	Click (Image:"M3/Configurations/configuration001/Personalization1", WaitFor:10)
	Click "M3/Configurations/configuration001/PersonalizationText"
	TypeText Return
	TypeText "My automated personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/BlockLettering"
	Click "M3/Configurations/configuration001/VVhiteColor"
	Click "M3/Configurations/configuration001/NoOrderNotes"
	Click "M3/Configurations/configuration001/DoubleStrap"
	(*Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if
	Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if
	Wait 3
	if ImageFound(5,"M3/Configurations/configuration001/WARNING") then
		Click "M3/Configurations/configuration001/OKButton"
	end if*)
end config001

to config002
	Click (Image:"M3/Configurations/config2/ProofRequired", WaitFor:136)
	Click (Image:"M3/Configurations/config2/NumCustomizations", WaitFor:30)
	Click "M3/Configurations/config2/Personalization"
	Click "M3/Configurations/config2/Application1"
	Click (279,242)
	TypeText Return
	TypeText "Acushnet script 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/BlockLettering"
	Click "M3/Configurations/configuration001/WhiteColor"
	Click "M3/Configurations/configuration001/NoOrderNotes"
end config002

to ConfigB1 
	Wait 5// has Tota 5 no. of Customizations.
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_No5"
	//Customization# 1{Logo }
	Click "M3/Configurations/configuration001/CustomizationLocation/JL023ApparelPocketL1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JL001Logo1"
	Click "M3/Configurations/configuration001/logoID/logoField/Logo1ID_Field"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
	end if
	click "M3/Configurations/configuration001/logoID/logoColorUp/JL058ColorCordnat"
	//Customization#2 {Pers}
	click "M3/Configurations/configuration001/CustomizationLocation/JL024_ApparelPocket_L2" //  Customization#2 :Location
	click "M3/Configurations/configuration001/personalizationType/customization2/JP002Pers2" // Select Pers 2 Option 
	Click "M3/Configurations/configuration001/PersonalizationText/PersonalizationTextPers2" // select to enter Personalization Text
	TypeText Return
	Click "M3/OIS101/PersonalizationField" // Click on Text Area
	TypeText "Test Pers 2"
	Click "M3/OIS101/PersonalizationNextButton"
	click "M3/Configurations/configuration001/BlockLettering"
	click  "M3/Configurations/configuration001/PersColor/JP052White"
	//Customization# 3{Logo}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL037 _SpinePocket_L1"
	Click "M3/Configurations/configuration001/personalizationType/Customization3/JL003Loqo3"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")then
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
	else
		Log "Logo ID not accepted"
		Exit handler
	end if
	Click "M3/Configurations/configuration001/logoID/logoColorUp/JL059SetColors"
	//Customization #4 {Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL057SpinePocketL2" //Location 4
	Click "M3/Configurations/configuration001/personalizationType/customization4/JP004Pers4"
	if ImageFound(3,"M3/Configurations/configuration001/PersonalizationText/PersonalizationTextPers4")
		TypeText Return
	end if
	Click "M3/OIS101/PersonalizationField" // Click on Text Area
	TypeText "Test Pers 4"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/persLettering/JP051Script"
	Click "M3/Configurations/configuration001/PersColor/JP053Gold"
	if ImageFound(3,"M3/Configurations/configuration001/SalesType/JP013Personalization")
		Click "M3/Configurations/configuration001/SalesType/JP013Personalization"
	end if
	//Customization #5 {Logo}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL038SideSaddlePocket"
	Click "M3/Configurations/configuration001/personalizationType/Customization5/JL056Logo5"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")then
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
	else
		Log "Logo ID not accepted"
		Exit handler
	end if
	Click "M3/Configurations/configuration001/logoID/logoColorUp/JL060OtherColor" 
	TypeText Return
	Click "M3/OIS101/PersonalizationField" // Click on Text Area
	TypeText "Test Special color instruction textbox"
	Click "M3/OIS101/PersonalizationNextButton"	
	Click "M3/Configurations/configuration001/YesOrderNotes"
	TypeText Return
	Click "M3/OIS101/PersonalizationField" // Click on Text Area
	TypeText "See Special Color Instruction"
	Click "M3/OIS101/PersonalizationNextButton"	
	Click "M3/Configurations/configuration001/StrapType/JST02Double1"
	wait 5
end ConfigB1

to ConfigB2 // Similar to B5
	Wait 5
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_EA3"
	//Customization# 1{Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL023ApparelPocketL1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JP001Pers1"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 1"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/persLettering/JP051Script"
	Click "M3/Configurations/configuration001/PersColor/JP054OtherColor"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Gray"
	Click "M3/OIS101/PersonalizationNextButton"
	//Customization# 2{Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL037 _SpinePocket_L1"
	Click "M3/Configurations/configuration001/personalizationType/customization2/JP002Pers2"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/persLettering/JP051Script"
	Click "M3/Configurations/configuration001/PersColor/JP054OtherColor"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Gray"
	Click "M3/OIS101/PersonalizationNextButton"
	// Customization# 3{Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL038SideSaddlePocket"
	Click "M3/Configurations/configuration001/personalizationType/Customization3/JP003Pers3"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 3"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/persLettering/JP051Script"
	Click "M3/Configurations/configuration001/PersColor/JP054OtherColor"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Gray"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/YesOrderNotes/YesJYES"
	TypeText Return
	Click "M3/OIS101/PersonalizationField" // Click on Text Area
	TypeText "See Special Color Instruction"
	Click "M3/OIS101/PersonalizationNextButton"	
	Click "M3/Configurations/configuration001/StrapType/JST03Single"
	wait 3
end ConfigB2

to ConfigB3 // similar to B5
	Wait 5
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_EA2"
	//Customization# 1{Logo}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL037 _SpinePocket_L1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JL001Logo1"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")then
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
	else
		Log "Logo ID not accepted"
		Exit handler
	end if
	Click "M3/Configurations/configuration001/logoID/logoColorUp/JL059SetColors"
	//Customization# 2{Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL057SpinePocketL2"
	Click "M3/Configurations/configuration001/personalizationType/customization2/JP002Pers2"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/Configurations/configuration001/persLettering/JP051Script"
	Click "M3/Configurations/configuration001/PersColor/JP054OtherColor"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Gray"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/OrderNotesButton","M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes", "M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes2"
	Click "M3/OIS101/DoubleStrapButton", "M3/Configurations/configuration001/StrapType/JST02Double"
end ConfigB3

to ConfigB4 // similar to B5
	Wait 5
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_EA2"
	//Customization# 1{Pers}
	Click "M3/Configurations/configuration001/CustomizationLocation/JL037 _SpinePocket_L1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JP001Pers1"
	//Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 1"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton","M3/Configurations/configuration001/persLettering/JP050Block"
	Click "M3/OIS101/ColorButton", "M3/Configurations/configuration001/PersColor/JP052White"
	//Customization# 2{Logo }
	Click "M3/Configurations/configuration001/CustomizationLocation/JL057SpinePocketL2"
	Click "M3/Configurations/configuration001/personalizationType/customization2/JL002Logo2"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")then
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
	else
		Log "Logo ID not accepted"
		Exit handler
	end if
	Click "M3/Configurations/configuration001/logoID/logoColorUp/JL058ColorCordnat"
	Click "M3/OIS101/OrderNotesButton","M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes", "M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes2"
	Click "M3/OIS101/DoubleStrapButton", "M3/Configurations/configuration001/StrapType/JST02Double"
end ConfigB4

to ConfigB5
	Wait 5
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_EA1"
	//Customization# 1{Logo }
	Click "M3/Configurations/configuration001/CustomizationLocation/JL023ApparelPocketL1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JL001Logo1"
	Click "M3/Configurations/configuration001/logoID/logoField/Logo1ID_Field"
	TypeText "376309"
	TypeText Return
	if ImageFound(5, "M3/Configurations/configuration001/logoID/logoID_OkWindow")then
		click "M3/Configurations/configuration001/logoID/logoID_OkWindow"
		else
		throw "Error","Logo ID not accepted"
	end if
	click "M3/Configurations/configuration001/logoID/logoColorUp/JL058ColorCordnat"
	
	Click "M3/OIS101/OrderNotesButton","M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes2","M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes"
	Click "M3/OIS101/DoubleStrapButton","M3/Configurations/configuration001/StrapType/DoubleStrap"
end ConfigB5

to ConfigB6
	Wait 5
	Click "M3/Configurations/configuration001/NumCustomization/NumCustomization_EA1"
	Click "M3/Configurations/configuration001/CustomizationLocation/JL037 _SpinePocket_L1"
	Click "M3/Configurations/configuration001/personalizationType/customization1/JP001Pers1"
	//Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Test Pers 1"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton","M3/Configurations/configuration001/persLettering/JP050Block"
	Click "M3/OIS101/ColorButton", "M3/Configurations/configuration001/PersColor/JP052White"
	Click "M3/OIS101/OrderNotesButton","M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes", "M3/Configurations/configuration001/NoOrderNotes/NoOrderNotes2"
	Click "M3/OIS101/DoubleStrapButton", "M3/Configurations/configuration001/StrapType/JST02Double"
end ConfigB6

to ConfigA2 // Needs to be tested
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/Configurations/configuration001/CustomizationLocation/LocationButtonSpineL1"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "Configuration: ConfigA2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end ConfigA2

To CobFigD1
	wait 3
	Click "M3/Configurations/DConfig/D1/czusUnitedStates"
	Click "M3/Configurations/DConfig/D1/CARHRightHand"
	Click "M3/Configurations/DConfig/D1/CBD105D105Driver"
	Click "M3/Configurations/DConfig/D1/CCGRPGraphite"
	Click "M3/Configurations/DConfig/D1/CJA1RRHLoftStdLieStdA1"
	Click "M3/Configurations/DConfig/D1/CZN0No"
	Click "M3/Configurations/DConfig/D1/CDA0SALDRogueSilver00SlkD"
	Click "M3/Configurations/DConfig/D1/StiffCES"
	Click "M3/Configurations/DConfig/D1/CI20STDStandardLength"
	Click "M3/Configurations/DConfig/D1/CFBTV10TTrVei360Sfk917716310"
	Click "M3/Configurations/DConfig/D1/CG20STDSlardardSize"
	Click "M3/Configurations/DConfig/D1/CXNNeutral"
	Click "M3/Configurations/DConfig/D1/CKD3STD12D3STD12GM"
	Click "M3/Configurations/DConfig/D1/CZN0No_1"
	wait 5
	
End CobFigD1

























