to login username, password
	Log "Logging in as " & username
	WaitFor 10, "M3/Login/InforPasswordSubmitButton"
	if ImageFound(3, "M3/Login/InforCapsLockNotfctn")then
		TypeText capsLockKey
		Click (330,447)
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText username
		TypeText tabKey                   //using Keyboard shortcut for less dependcy on images.
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText password
		TypeText returnKey            //using Keyboard shortcut for less dependcy on images.
	else
		Click (Image:"M3/Login/UsernameField", waitFor:10)
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText username
		Click (Image:"M3/Login/PasswordField", waitFor:10)
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText password
		Click "M3/Login/InforPasswordSubmitButton"
	end if
end login


To loginM3 userName, password
	set ExcelFile to workbook(ResourcePath("ZCustomaization.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1") 
	Put Cell(worksheet,A2) into username
	Put Cell(worksheet,B2) into password
	
	Log "Logging in as " & username
	WaitFor 10, "M3/Login/InforPasswordSubmitButton"
	Click "M3/Login/UsernameField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText username
	Click "M3/Login/PasswordField"
	TypeText password
	Click "M3/Login/InforPasswordSubmitButton"
End loginM3










