to openMWS060
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "MWS060"
	Click  "M3/Home/SearchSubmit"
end openMWS060

to enterWHItemLoc WHNumber,ItemNumber
	wait 5
	click "M3/MWS060/Whs"
	typetext controlkey,"a"
	typetext deletekey
	typetext WHNumber
	wait 2
	click "M3/MWS060/Itemnumber"
	typetext controlkey,"a"
	typetext deletekey
	typetext ItemNumber
	wait 2
	click "M3/MWS060/Location"
	typetext controlkey,"a"
	typetext deletekey
	typetext "MPF"
	Click "M3/PPS300/Next"
	wait 2
end enterWHItemLoc

to captureMPFLocation ItemNumber
	Click "M3/MWS060/Highlightlocation"
	Put readtext(252,440,305,451) into Item1
	if Item1 = ItemNumber then
		put readtext(467,428,526,441) into MPF
		If MPF <> "" then
			Logsuccess "Location for tyhe item was:- "&MPF
			return MPF
		else
			Logwarning "Location was not Captured"
		End If
	End If
end captureMPFLocation

to CaptureINSPLoc WHNumber,ItemNumber
	click "M3/MWS060/Whs"
	typetext controlkey,"a"
	typetext deletekey
	typetext WHNumber
	wait 2
	click "M3/MWS060/Itemnumber"
	typetext controlkey,"a"
	typetext deletekey
	typetext ItemNumber
	wait 2
	click "M3/MWS060/Location"
	typetext controlkey,"a"
	typetext deletekey
	typetext "INSP"
	Click "M3/PPS300/Next"
	wait 2
	
end CaptureINSPLoc

to ReadINSP ItemNumber
	Click "M3/MWS060/Highlightlocation"
	Put readtext(252,440,305,451) into Item1
	if Item1 = ItemNumber then
		put readtext(462,429,536,439) into INSP
		If INSP begins with "INSP" then
			Logsuccess "Location for tyhe item was:- "&INSP
			return INSP
		else
			Logwarning "Location was not Captured"
		End If
	End If
	
end ReadINSP

To CloseMWS060
	Click "M3/PPS300/XClose"
	wait 5
End CloseMWS060




