to recordCONumber
	WaitFor 30, "M3/OIS101/OIS101B1Title"
	DoubleClick "M3/OIS101/CONumberField"
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click (30,700)
	TypeText controlKey, "v"
	repeat 2 times
		TypeText spacebar
	end repeat
	set coNumber to ReadText(((12,695),(75,711)))
	Log coNumber
	Click "M3/OIS101/WindowsButton"
	return coNumber
end recordCONumber

//***************** to store CO no directly into variable ************************
to storeCONum 
	put ImageLocation("M3/OIS101/CONumberField/CONumberField_new1") into SR
	put SR +(-40,-10) into P1
	put SR +(87,10) into P2
	put ReadText((P1), (P2)) into CoNumber
	Log CoNumber
	Return CoNumber
end storeCONum

to recordPONumber
	"M3/OIS101".supplyChain
	Drag "M3/OIS101/OrderDrag"
	MoveTo (250,221)
	Drop
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS101/WindowsSearchField"
	TypeText controlKey, "v"
	repeat 5 times
		TypeText spacebar
	end repeat
	set poNumber to ReadText((imageLocation("M3/OIS101/WindowPasteA")+(-237,1), imageLocation("M3/OIS101/WindowPasteB") + (-167,16)))
	Log poNumber
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS300/CloseButton"
	return poNumber
end recordPONumber

to supplyChain
	Click (Image:"M3/OIS101/OrderLineLine", WaitFor:6.1)
	Click "M3/OIS101/SupplyChainLink"
end supplyChain

to enterItemCode ItemCode
	WaitFor 30, "M3/OIS101/OIS101B1Title"
	Click (187,595)
	TypeText itemCode
	TypeText Return
end enterItemCode

to enterItemQuantity productQuantity
	Click "M3/OIS101/ItemQuantity"
	TypeText productQuantity
	TypeText Return
end enterItemQuantity

to EnterTransResonCode TranctionResonCode
	Click "M3/OIS101/TransactionReason"
	TypeText TranctionResonCode
end EnterTransResonCode

to BlanketAgreement BlanketAgreement
	Click "M3/OIS101/BlanketAgreement"
	TypeText BlanketAgreement
end BlanketAgreement

to enterItemColor
	Click (130,300)
	TypeText "1"
	Click "M3/OIS101/ConfiqStyleButton"
end enterItemColor	

to enterItemColorNewEra
	Click "M3/OIS101/NewEraColorField"
	TypeText "12"
	Click "M3/OIS101/ConfiqStyleButton"
end enterItemColorNewEra

to configuratorA
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/OIS101/LocationButton"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end configuratorA



to configuratorNewEra
	Wait 5
	Click "M3/OIS101/NewEra/ProofRequiredButton"
	Click "M3/OIS101/NewEra/TitleistButton"
	Click "M3/OIS101/NewEra/ColorButton"
	Click "M3/OIS101/NewEra/OutlineYesButton"
	Click (Image:"M3/OIS101/NewEra/OutlineColorButton", WaitFor:21)
	Click "M3/OIS101/NewEra/2Customizations"
	Click "M3/OIS101/NewEra/Location1Button"
	Click "M3/OIS101/NewEra/Customization1Button"
	TypeText Return
	TypeText "My Automated Personalization 1"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/NewEra/LetteringButton"
	Click "M3/OIS101/NewEra/ShapeButton"
	Click "M3/OIS101/NewEra/ColorButton2"
	Click "M3/OIS101/NewEra/Location2"
	Click "M3/OIS101/NewEra/Customization2"
	TypeText Return
	TypeText "My Automated Personalization 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/NewEra/LetteringButton"
	Click "M3/OIS101/NewEra/ShapeButton"
	Click "M3/OIS101/NewEra/ColorButton2"
	Click "M3/OIS101/OrderNotesButton"
end configuratorNewEra

to closeFromOrderLines
	//Close OIS101B1
	WaitFor 60, "M3/OIS101/OIS101B1Title"
	Click "M3/OIS101/XCloseButton"
	//Close OIS110E
	WaitFor 30, "M3/OIS101/OIS110ETitle"
	Click "M3/OIS101/XCloseButton"
	//Close OIS100A
	WaitFor 30, "M3/OIS101/OIS100ATitle"
	Click "M3/OIS101/XCloseButton"
	WaitFor 30, "M3/OIS101/OIS300BTitle"
	Click "M3/OIS101/XCloseButton"
end closeFromOrderLines

to closeOrderLines
	//Close OIS101B1
	WaitFor 60, "M3/OIS101/OIS101B1Title"
	Click "M3/OIS101/XCloseButton"
	//Close OIS110E
	WaitFor 30, "M3/OIS101/OIS110ETitle"
	Click "M3/OIS101/XCloseButton"
	//Close OIS100A
	WaitFor 30, "M3/OIS101/OIS100ATitle"
	Click "M3/OIS101/XCloseButton"
end closeOrderLines











