to recordCONumber
	WaitFor 60, "M3/OIS101/OIS101B1Title"
	DoubleClick "M3/OIS101/CONumberField"
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click (30,700)
	TypeText controlKey, "v"
	repeat 2 times
		TypeText spacebar
	end repeat
	set coNumber to ReadText(((12,695),(75,711)))
	Log coNumber
	Click "M3/OIS101/WindowsButton"
	return coNumber
end recordCONumber

//***************** to store CO no directly into variable ************************
to storeCONum 
	put ImageLocation("M3/OIS101/CONumberField/CONumberField_new1") into SR
	put SR +(-40,-10) into P1
	put SR +(87,10) into P2
	put ReadText((P1), (P2)) into CoNumber
	Log CoNumber
	Return CoNumber
end storeCONum

to recordPONumber
	"M3/OIS101".supplyChain
	Drag "M3/OIS101/OrderDrag"
	MoveTo (250,221)
	Drop
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS101/WindowsSearchField"
	TypeText controlKey, "v"
	repeat 5 times
		TypeText spacebar
	end repeat
	set poNumber to ReadText((imageLocation("M3/OIS101/WindowPasteA")+(-237,1), imageLocation("M3/OIS101/WindowPasteB") + (-167,16)))
	Log poNumber
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS300/CloseButton"
	return poNumber
end recordPONumber

to supplyChain
	Click (Image:"M3/OIS101/OrderLineLine", WaitFor:6.1)
	Click "M3/OIS101/SupplyChainLink"
end supplyChain

to enterItemCode ItemCode
	WaitFor 30, "M3/OIS101/OIS101B1Title"
	Click (187,595)
	wait 1
	TypeText itemCode
	TypeText Return
end enterItemCode

to enterItemQuantity productQuantity
	Click "M3/OIS101/ItemQuantity"
	TypeText productQuantity
	TypeText Return
end enterItemQuantity

To enterWhearhouseNumb WHNumber
	Click image( "M3/OIS101/whm")
	TypeText WHNumber
	TypeText Return
	
	
End enterWhearhouseNumb


to enterTransResonCode tranctionResonCode
	if tranctionResonCode <>"" then
		Click "M3/OIS101/TransactionReason"
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText TranctionResonCode
	end if
end enterTransResonCode

to BlanketAgreement BlanketAgreement
wait 10
	//click "M3/OIS101/lineItem"
	"M3/OIS101".ChangeViewInOis101
	Click "M3/OIS101/PromoDiscprice"
	if BlanketAgreement <> "" then
		Click "M3/OIS101/BlanketAgreement"
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText BlanketAgreement
	end if
	wait 2
	DoubleClick "M3/OIS101/0ApplyAgreemen"
	wait 4
	If ImageFound("M3/OIS101/BlanketAgr") then
		Put ReadText((373,291),(424,300)) into BlanketAgreement1
		if BlanketAgreement1 = BlanketAgreement then
			LogSuccess "BlanketAgreement is Applied to line Item was:-  "&BlanketAgreement1
		else if BlanketAgreement <>"" then
			
			LogSuccess  "BlanketAgreement is Applied to line Item was:-  "&BlanketAgreement
			
		else
			LogError  "BlanketAgreement Not Applied to lthe ine Item"
			
		End If
		
	End If
	
	
end BlanketAgreement

To setPromocode

	Click "M3/OIS101/Actions"
	Wait 2
	Click "M3/OIS101/Settinqs"
	wait 2
	Click "M3/OIS101/InputAlternativePanelB_1"
	//Click "M3/OIS101/9WhsItpprom"
	Click "M3/OIS101/9Whslipprom"
	Click "M3/OIS101/Next"
	Wait 2
End setPromocode

To EnterPromoCode PromoCod
	Click "M3/OIS101/Prom"
	TypeText PromoCod
End EnterPromoCode

to getPromocodevalue
	//Click "M3/OIS101/SelectItemNum"
	Click (Image:"M3/OIS101/selectline", WaitFor:45)
	//Click "M3/OIS101/PromoDiscValue"
	Click "M3/OIS101/PromoDiscprice"
	put  ImageLocation ("M3/OIS101/PromoDiscprice") into loc
	Put loc+(-20,-16) into L1
	Put loc+(61,15) into L2
	put  ReadText((L1), (L2)) into PromoDiscValue
	
	Log PromoDiscValue
	If PromoDiscValue <> "" then
		LogSuccess "Promo Code was Applied to the Item  with value of"&"  "& PromoDiscValue
	End If
	return PromoDiscValue
	
end getPromocodevalue

To ChangeViewInOis101
	Click "M3/OIS101/View_1"
	wait 2
	TypeText homeKey
	wait 5
	Click  "M3/OIS101/G5L01004PriceDiscounts"
End ChangeViewInOis101


to enterItemColor
	Click (130,300)
	TypeText "1"
	Click Image:"M3/OIS101/ConfiqStyleButton", WaitFor:10
end enterItemColor	

to enterItemColorNewEra
	Click "M3/OIS101/NewEraColorField"
	TypeText "12"
	Click "M3/OIS101/ConfiqStyleButton"
end enterItemColorNewEra

to configuratorA
	Wait 5
	Click "M3/OIS101/NumApplicationsButton"
	Click "M3/OIS101/LocationButton"
	Click "M3/OIS101/PersonalizationButton"
	Click "M3/OIS101/PersonalizationTextButton"
	TypeText Return
	Click "M3/OIS101/PersonalizationField"
	TypeText "My Automated Personalization"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/LetteringButton"
	Click "M3/OIS101/ColorButton"
	Click "M3/OIS101/OrderNotesButton"
	Click "M3/OIS101/DoubleStrapButton"
end configuratorA



to configuratorNewEra
	Wait 5
	Click "M3/OIS101/NewEra/ProofRequiredButton"
	Click "M3/OIS101/NewEra/TitleistButton"
	Click "M3/OIS101/NewEra/ColorButton"
	Click "M3/OIS101/NewEra/OutlineYesButton"
	Click (Image:"M3/OIS101/NewEra/OutlineColorButton", WaitFor:21)
	Click "M3/OIS101/NewEra/2Customizations"
	Click "M3/OIS101/NewEra/Location1Button"
	Click "M3/OIS101/NewEra/Customization1Button"
	TypeText Return
	TypeText "My Automated Personalization 1"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/NewEra/LetteringButton"
	Click "M3/OIS101/NewEra/ShapeButton"
	Click "M3/OIS101/NewEra/ColorButton2"
	Click "M3/OIS101/NewEra/Location2"
	Click "M3/OIS101/NewEra/Customization2"
	TypeText Return
	TypeText "My Automated Personalization 2"
	Click "M3/OIS101/PersonalizationNextButton"
	Click "M3/OIS101/NewEra/LetteringButton"
	Click "M3/OIS101/NewEra/ShapeButton"
	Click "M3/OIS101/NewEra/ColorButton2"
	Click "M3/OIS101/OrderNotesButton"
end configuratorNewEra

to closeFromOrderLines
	//Close OIS101B1
	WaitFor 180, "M3/OIS101/OIS101B1Title"
	Wait 3
	Click "M3/OIS101/XCloseButton"
	//Close OIS110E
	WaitFor 30, "M3/OIS101/OIS110ETitle"
	Wait 3
	Click "M3/OIS101/XCloseButton"
	Wait 3
	if ImageFound("M3/OIS300/CreditLimit") then
		Click "M3/OIS300/CreditLimit"
	end if
	//Close OIS100A
	WaitFor 30, "M3/OIS101/OIS100ATitle"
	Wait 3
	Click "M3/OIS101/XCloseButton"
	WaitFor 30, "M3/OIS101/OIS300BTitle"
	Wait 3
	Click "M3/OIS101/XCloseButton"
end closeFromOrderLines

to closeOrderLines
	//Close OIS101B1
	WaitFor 60, "M3/OIS101/OIS101B1Title"
	Click "M3/OIS101/XCloseButton"
	//Close OIS110E
	WaitFor 30, "M3/OIS101/OIS110ETitle"
	Click "M3/OIS101/XCloseButton"
	//Close OIS100A
	WaitFor 30, "M3/OIS101/OIS100ATitle"
	Click "M3/OIS101/XCloseButton"
end closeOrderLines

to close
	WaitFor 180, "M3/OIS101/OIS101B1Title"
	Wait 3
	Click "M3/OIS101/XCloseButton"
end close











