//Requires M3/Login
to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "OIS350"
	Click "M3/Home/SearchSubmit"
end open


to recordInvoiceDate
	Click "M3/OIS350/InvoiceDate"
	put  ImageLocation ("M3/OIS350/InvoiceDate") into loc
	Put loc+(-70,-20) into L1
	Put loc+(90,35) into L2
	put  ReadText((L1), (L2)) into InvoiceDate
	Log InvoiceDate
	return InvoiceDate
end recordInvoiceDate


