//Requires M3/Login
to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "OIS300"
	Click "M3/Home/SearchSubmit"
end open

to startNewOrder
	Click (Image:"M3/OIS300/NewOrderButton_new", WaitFor:60), 
end startNewOrder

to enterCustomerNumber customerNumber, coType
	Click "M3/OIS300/CustomerNumberField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText customerNumber
	TypeText Return
	TypeText coType
	Wait 2
	if coType is "USO" then
		Click "M3/OIS300/NextButton"
	end if
	(*TypeText Return*)
end enterCustomerNumber

to submitOIS100A
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100A

to enterCustomersPO PO
	Click "M3/OIS300/CustomersPOField"
	TypeText PO
end enterCustomersPO


to submitOIS100G
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100G

to acceptPOWarning
	Wait 5
	Click (Image:"M3/OIS300/WARNINGOkButton", WaitFor:5)
	(*Click "M3/OIS300/OkButton"*)
	MoveTo "Corner"
end acceptPOWarning

to submitOIS100F
	Wait 3
	(*WaitFor 8.0, "M3/OIS300/OIS100FTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100F

to submitOIS100H
	Wait 3
	(*WaitFor 8.0, "M3/OIS300/OIS100HTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100H

to submitOIS100E
	Wait 3
	(*WaitFor 8.0, "M3/OIS300/OIS100ETitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100E

to enterOIS100E deliveryDate
	Click "M3/OIS300/RequestedDelyDateField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText 101117
	TypeText Return
	MoveTo "Corner"
end enterOIS100E

to submitOIS102H
	Wait 5
	(*WaitFor 8.0, "M3/OIS300/OIS102HTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS102H

to lookupCO coNumber
	Click "M3/OIS300/CoField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText coNumber
	TypeText Return
	Click "M3/OIS300/HighlightCO"
end lookupCO

to openDeliveryToolbox
	Click "M3/OIS300/HighlightCO"
	Click "M3/OIS300/DeliveryToolboxLink"
end openDeliveryToolbox

to confirmStatusPacked
	assert "M3/OIS300".checkPackingStatus is SUCCESS, "Packing status update in delivery toolbox"
end confirmStatusPacked

function checkPackingStatus
	repeat 2 minutes
		if imageFound(3,"M3/OIS300/PackingStatusPacked") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkPackingStatus

to updatePickList
	Click "M3/PMS100/DeliveryOrderLine"
	Click "M3/PMS100/PickingListsLink"
	KeyDown ControlKey
	repeat 6 times
		TypeText "="
	end repeat
	KeyUp ControlKey
	Click "M3/PMS100/MWS420B1OrderLine"
	Click "M3/PMS100/ConfirmIssuesLink"
	assert "M3/PMS100".checkPickingStatusImage is SUCCESS, "Picking status update in picking lists"
	KeyDown ControlKey
	repeat 6 times
		TypeText "-"
	end repeat
	KeyUp ControlKey
	Click "M3/PMS100/CloseButton"
end updatePickList

to confirmStatusShipped
	assert "M3/OIS300".checkShippingStatus is SUCCESS, "Shipping status update in delivery toolbox"
end confirmStatusShipped

to checkShippingStatus
	repeat 45 minutes
		if imageFound(20, "M3/OIS300/ShippingStatusPacked") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkShippingStatus

to closeFromDeliveryToolbox
	Click "M3/OIS300/CloseButton"
	MoveTo "Corner"
	Click "M3/OIS300/CloseButton"
	MoveTo "Corner"
end closeFromDeliveryToolbox

to recordDeliveryNumber
	(*	set deliveryNumber to ReadText((imageLocation("M3/OIS300/DeliveryNumberA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log deliveryNumber
	return deliveryNumber*)
	Drag "M3/OIS300/DelyNoDrag"
	MoveTo (81,279)
	Drop
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS101/WindowsSearchField"
	TypeText controlKey, "v"
	repeat 5 times
		TypeText spacebar
	end repeat
	set deliveryNumber to ReadText((imageLocation("M3/OIS101/WindowPasteA")+(-237,1), imageLocation("M3/OIS101/WindowPasteB") + (-167,16)))
	Log deliveryNumber
	Click "M3/OIS101/WindowsButton"
	return deliveryNumber
end recordDeliveryNumber

to recordOrderData
	set orderDate to ReadText((imageLocation("M3/OIS300/OrderDateA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log orderDate
end recordOrderData

to reschedule
	Click "M3/OIS300/HighlightCO"
	Click "M3/OIS300/RescheduleLink"
	Wait 5
	TypeText "081617"
	TypeText Return
	Click (Image:"M3/OIS300/UpdateButton", WaitFor:3.3)
	Click "M3/OIS300/CloseButton"
end reschedule

to close
	Click "M3/OIS300/CloseButton"
end close
