//Requires M3/Login
to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "OIS300"
	Click "M3/Home/SearchSubmit"
end open

to startNewOrder
	Click (Image:"M3/OIS300/NewOrderButton", WaitFor:40)
end startNewOrder

to enterCustomerNumber
	Click "M3/OIS300/CustomerNumberField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText US00025065
	TypeText Return
end enterCustomerNumber

to submitOIS100A
	Click "M3/OIS300/NextButton"
end submitOIS100A

to enterCustomersPO PO
	Click "M3/OIS300/CustomersPOField"
	TypeText PO
end enterCustomersPO

to submitOIS100G
	Click "M3/OIS300/NextButton"
end submitOIS100G

to acceptPOWarning
	Click "M3/OIS300/OkButton"
end acceptPOWarning

to submitOIS100F
	WaitFor 8.0, "M3/OIS300/OIS100FTitle"
	Click "M3/OIS300/NextButton"
end submitOIS100F

to submitOIS100H
	WaitFor 8.0, "M3/OIS300/OIS100HTitle"
	Click "M3/OIS300/NextButton"
end submitOIS100H

to submitOIS100E
	WaitFor 8.0, "M3/OIS300/OIS100ETitle"
	Click "M3/OIS300/NextButton"
end submitOIS100E

to submitOIS102H
	WaitFor 8.0, "M3/OIS300/OIS102HTitle"
	Click "M3/OIS300/NextButton"
end submitOIS102H

to lookupCO coNumber
	TypeText "3013690225"
	TypeText Return
end lookupCO

to openDeliveryToolbox
	Click "M3/OIS300/HighlightCO"
	Click "M3/OIS300/DeliveryToolboxLink"
end openDeliveryToolbox

to confirmStatusPacked
	assert "M3/OIS300".checkPackingStatus is SUCCESS, "Packing status update in delivery toolbox"
end confirmStatusPacked

function checkPackingStatus
	repeat 2 minutes
		if imageFound(3,"M3/OIS300/PackingStatusPacked") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkPackingStatus

to closeFromDeliveryToolbox
	Click "M3/OIS300/CloseButton"
	Click "M3/OIS300/CloseButton"
end closeFromDeliveryToolbox

to recordDeliveryNumber
	set deliveryNumber to ReadText((imageLocation("M3/OIS300/DeliveryNumberA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log deliveryNumber
	return deliveryNumber
end recordDeliveryNumber

to recordOrderData
	set orderDate to ReadText((imageLocation("M3/OIS300/OrderDateA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log orderDate
end recordOrderData
