//Requires M3/Login
to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "OIS300"
	Click "M3/Home/SearchSubmit"
end open

to startNewOrder
	Click (Image:"M3/OIS300/NewOrderButton_new", WaitFor:120)
end startNewOrder

to enterCustomerNumber customerNumber, coType, SalesHold
	Click "M3/OIS300/CustomerNumberField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText customerNumber
	TypeText Return
	log coType
	if coType is not empty then
		TypeText coType
	end if
	Wait 2
	if SalesHold <> "" then
		wait 2
		Click "M3/OIS100/SalesHoldCode"
		TypeText SalesHold
		TypeText return
	End If
	Click "M3/OIS300/NextButton"
	if ImageFound(3, "M3/OIS300/promotionOrExpns") then
		Repeat 2 times
			TypeText Return
		End repeat
		
	end if
	(*if coType is "USO" then
		Click "M3/OIS300/NextButton"
	else if coType is "USA" then
		Click "M3/OIS300/NextButton"
		
	end if*)
	(*TypeText Return*)
end enterCustomerNumber

to submitOIS100A
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100A

to enterCustomersPO PO
	Click "M3/OIS300/CustomersPONumber"
	TypeText PO
end enterCustomersPO

to TagField TagField
	//DoubleClick "M3/OIS300/TagForHeaderLevel"
	DoubleClick  "M3/OIS101/TagForHeaderLevel_1"
	
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText TagField
	wait 2
end TagField

to DeliveryTerm DeliveryTerm
	if DeliveryTerm is not empty then
		//DoubleClick "M3/OIS300/DeliveryTerms"
		DoubleClick "M3/OIS100/DeliveryTerms"
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText DeliveryTerm
	end if
end DeliveryTerm

To DeliveryMethod DeliveryMethod
	if DeliveryMethod is not empty then
		//DoubleClick "M3/OIS300/DeliveryMethod"
		DoubleClick "M3/OIS100/DeliveryMethod"
		TypeText controlKey, "a"
		TypeText deleteKey
		TypeText DeliveryMethod
	end if
End DeliveryMethod

to submitOIS100G
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100G

to acceptPOWarning	
	if ImageFound(ImageName:"M3/OIS300/WARNING", WaitFor:5) then
		Click "M3/OIS300/WARNINGOkButton"
		(*Click "M3/OIS300/OkButton"*)
		MoveTo "Corner"
	end if
end acceptPOWarning

to submitOIS100F
	(*WaitFor 8.0, "M3/OIS300/OIS100FTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100F

to submitOIS100H
	(*WaitFor 8.0, "M3/OIS300/OIS100HTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100H

to submitOIS100E priority
	if priority is not empty then
		if priority is "7" then
			Click "M3/OIS300/PriorityDropdown"
			TypeText endKey
			TypeText upArrow
			TypeText upArrow
			TypeText return
		else
			throw "Unsupported Priority","this priority is not supported in M3/OIS300 function submitOIS100E"
		end if
	end if
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS100E

to enterOIS100E deliveryDate
	Click "M3/OIS300/RequestedDelyDateField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText 101117
	TypeText Return
	MoveTo "Corner"
end enterOIS100E

to submitOIS102H
	(*WaitFor 8.0, "M3/OIS300/OIS102HTitle"*)
	Click "M3/OIS300/NextButton"
	MoveTo "Corner"
end submitOIS102H

to lookupCO coNumber
	Click "M3/OIS300/CoField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText coNumber
	TypeText Return
	Click "M3/OIS300/HighlightCO"
end lookupCO

to openDeliveryToolbox
	RightClick "M3/OIS300/HighlightCO"
	if ImageFound (3,"M3/OIS300/relateddropdown")
		Click "M3/OIS300/relateddropdown"
		Click "M3/OIS300/DeliveryToolboxLink"
	else 
		Click "M3/OIS300/HighlightCO"
		TypeText "controlKey","43"
	end if
	
end openDeliveryToolbox



to confirmStatusPacked
	assert "M3/OIS300".checkPackingStatus is SUCCESS, "Packing status update in delivery toolbox"
end confirmStatusPacked

function checkPackingStatus
	repeat 2 minutes
		
		if imageFound(3,"M3/OIS300/PackingStatusPacked") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat		
else
Log ("Image not found")


end checkPackingStatus

to updatePickList
	Click "M3/PMS100/DeliveryOrderLine"
	Click "M3/PMS100/PickingListsLink"
	KeyDown ControlKey
	repeat 6 times
		TypeText "="
	end repeat
	KeyUp ControlKey
	Click "M3/PMS100/MWS420B1OrderLine"
	Click "M3/PMS100/ConfirmIssuesLink"
	assert "M3/PMS100".checkPickingStatusImage is SUCCESS, "Picking status update in picking lists"
	KeyDown ControlKey
	repeat 6 times
		TypeText "-"
	end repeat
	KeyUp ControlKey
	Click "M3/PMS100/CloseButton"
end updatePickList

to confirmStatusShipped
	assert "M3/OIS300".checkShippingStatus is SUCCESS, "Shipping status update in delivery toolbox"
end confirmStatusShipped

to checkShippingStatus
	repeat 45 minutes
		if imageFound(20, "M3/OIS300/ShippingStatusPacked") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkShippingStatus

to closeFromDeliveryToolbox
	Click "M3/OIS300/CloseButton"
	MoveTo "Corner"
	Click "M3/OIS300/CloseButton"
	MoveTo "Corner"
end closeFromDeliveryToolbox

to recordDeliveryNumber
	(*	set deliveryNumber to ReadText((imageLocation("M3/OIS300/DeliveryNumberA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log deliveryNumber
	return deliveryNumber*)
	Drag "M3/OIS300/DelyNoDrag"
	MoveTo (81,279)
	Drop
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	Click "M3/OIS101/WindowsSearchField"
	TypeText controlKey, "v"
	repeat 5 times
		TypeText spacebar
	end repeat
	set deliveryNumber to ReadText(((12,695),(75,711))) //ReadText((imageLocation("M3/OIS101/WindowPasteA")+(-237,1), imageLocation("M3/OIS101/WindowPasteB") + (-167,16)))
	Log deliveryNumber
	Click "M3/OIS101/WindowsButton"
	return deliveryNumber
end recordDeliveryNumber

to recordOrderData
	set orderDate to ReadText((imageLocation("M3/OIS300/OrderDateA"), imageLocation("M3/OIS300/DeliveryNumberB")))
	Log orderDate
end recordOrderData

to reschedule
	Click "M3/OIS300/HighlightCO"
	Click "M3/OIS300/RescheduleLink"
	Wait 5
	TypeText "081617"
	TypeText Return
	Click (Image:"M3/OIS300/UpdateButton", WaitFor:3.3)
	Click "M3/OIS300/CloseButton"
end reschedule

to setZoom80prcnt
	if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton105") then
		Click "M3/OIS300/ZoomButton/ZoomButton105"
		Click "M3/OIS300/ZoomButton/slct80frm105"
	else if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton100") then
		Click "M3/OIS300/ZoomButton/ZoomButton100"
		Click "M3/OIS300/ZoomButton/slct80frm100"
	else if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton95") then
		Click "M3/OIS300/ZoomButton/ZoomButton95"
		Click "M3/OIS300/ZoomButton/slct80frm95"
	else if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton90") then
		Click "M3/OIS300/ZoomButton/ZoomButton90"
		Click "M3/OIS300/ZoomButton/slct80frm90"
	else if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton85") then
		Click "M3/OIS300/ZoomButton/ZoomButton85"
		Click "M3/OIS300/ZoomButton/slct80frm85"//,"M3/OIS300/slct80frm85hgltd"
	else if ImageFound (3,"M3/OIS300/ZoomButton/ZoomButton80") then
		Click "M3/OIS300/ZoomButton/ZoomButton80"
		Click "M3/OIS300/ZoomButton/slct80frm80"
	else if ImageFound(3,"M3/OIS300/ZoomButton/ZoomButton75") then
		Click "M3/OIS300/ZoomButton/ZoomButton75"
		Click "M3/OIS300/ZoomButton/slct80frm75"
	end if
	
end setZoom80prcnt

to zoom75prcnt
	// set the page to 80 percent zoom from present state using "setZoom80prcnt"
	"M3/OIS300".setZoom80prcnt
	WaitFor 5, "M3/OIS300/ZoomButton/ZoomButton80"
	Click (350,170) // click on blank area
	KeyDown controlKey
	repeat 2 times
		TypeText "-"	
	end repeat
	KeyUp controlKey
end zoom75prcnt

to zoom85prcnt
	// set the page to 80 percent zoom from present state using "setZoom80prcnt"
	"M3/OIS300".setZoom80prcnt
	if ImageFound (5, "M3/OIS300/ZoomButton/ZoomButton80")
		
		Click (350,170)
		KeyDown controlKey
		repeat 2 times
			TypeText "+"	
		end repeat
		KeyUp controlKey
	end if
end zoom85prcnt

to zoom90prcnt
	// set the page to 80 percent zoom from present state using "setZoom80prcnt"
	"M3/OIS300".setZoom80prcnt
	if ImageFound (5, "M3/OIS300/ZoomButton/ZoomButton80")
		Click (350,170)
		KeyDown controlKey
		repeat 3 times
			TypeText "+"	
		end repeat
		KeyUp controlKey
	end if
end zoom90prcnt

to zoom105prcnt
	// set the page to 80 percent zoom from present state using "setZoom80prcnt"
	"M3/OIS300".setZoom80prcnt
	if ImageFound (5, "M3/OIS300/ZoomButton/ZoomButton80")
		Click (350,170)
		KeyDown controlKey
		repeat 6 times
			TypeText "+"	
		end repeat
		KeyUp controlKey
	end if
end zoom90prcnt


to close
	Click "M3/OIS300/CloseButton"
end close

to recordDepartDate
	Click "M3/OIS300/DepartDate"
	put  ImageLocation ("M3/OIS300/DepartDate") into loc
	Put loc+(-60,-10) into L1
	Put loc+(75,10) into L2
	put  ReadText((L1), (L2)) into Departdate
	Log Departdate
	return Departdate
end recordDepartdate

to openDeliveryToolboxlink
	
	Click "M3/OIS300/HighlightCOnum"
	Click "M3/OIS300/relateddropdown"
	Click "M3/OIS300/Relateddropdownlist"
	Click "M3/OIS300/Deliverytoolbox"
end openDeliveryToolboxlink

to recordOrderDate 
	set orderDate to ReadText(imageLocation ("M3/OIS300/Orderdate"))
	Log orderDate
end recordOrderDate
