to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PMS070"
	Click "M3/Home/SearchSubmit"
end open

to checkfacility
	WaitFor 20, "M3/PMS070/Facility"
	Click "M3/PMS070/Facility"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText "061"
	TypeText Return
end checkfacility



to checkMOStatus
	repeat 4 minutes
		if imageFound(60,"M3/PMS070/MOStatus60") then
			Log "MO status is 60"
			return SUCCESS
			
		else If imageFound(99,"M3/PMS070/MOStatus9099") then
			Log "MO status is 90"		
		Else
			Log "Image not found"
		End if
		
		Click "M3/PMS100/Refresh"
		
	end checkMOStatus

to lookupMOnumber
	"M3/PMS070".open
	"M3/PMS070".checkfacility
	// to enter MO number
	Click  "M3/PMS070/MOnumber"
	TypeText controlKey, "a"
	TypeText deleteKey
	//manually entering MO number
	TypeText "1000004399"
	TypeText Return
end lookupMOnumber


to compareOrderandManufQuantity

	Click "M3/PMS070/OrderqtybUM"
	
	set orderqty to readtext(imageFound("M3/PMS070/OrderqtybUM"))
	
	Click "M3/PMS070/Manufquantity"
	
	set manufactqty to  readtext(imageFound("M3/PMS070/Manufquantity"))
	
	if orderqty = manufactqty then
		logsucces "orderqty"&orderqty&"is Equal to"&"manufactqty"&manufactqty
	else
		Logerror "Order QTy & Manufatuer Qty are not equal"
	end if
	
end compareOrderandManufQuantity




to compareRemainsandManufQuantity

	Click "M3/PMS070/RemainsField"
	
	set remainsvalue to readtext(imageFound("M3/PMS070/RemainsField"))
	
	Click "M3/PMS070/Manufquantity"
	
	set manufactqty to  readtext(imageFound("M3/PMS070/Manufquantity"))
	
	if remainsvalue= null& & manufactqty<>null then
		logsuccess "remainsvalue"&remainsvalue&"moved to"&"manufactqty"&manufactqty
	else
		Logerror "Remains values hasnt moved to manufactqty"
	end if
	
end compareRemainsandManufQuantity






