to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PMS070"
	Click "M3/Home/SearchSubmit"
end open

to lookupMO moNumber
	DoubleClick (142,240)
	TypeText "061"
	Click "M3/PMS070/MOnumberLookup"
	TypeText moNumber
	TypeText Return
end lookupMO

(*
to open MoNumber
	WaitFor 20, "M3/Application/M3"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PPS070"
	Click "M3/Home/SearchSubmit"
end open*)