to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PMS100"
	Click "M3/Home/SearchSubmit"
end open

to lookupSchedule scheduleNumber
	Click "M3/PMS100/SortingOrderDropdown"
	TypeText homeKey
	repeat 6 times
		TypeText downArrow
	end repeat
	TypeText Return
	Click "M3/PMS100/ViewDropdown"
	TypeText homeKey
	repeat 8 times
		TypeText downArrow
	end repeat
	TypeText Return
	WaitFor 20, "M3/PMS100/FacilityField"
	Click "M3/PMS100/FacilityField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText "061"
	TypeText Return
	Click "M3/PMS100/Product"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS100/MONumberField"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS100/Scheduleno100"
	TypeText scheduleNumber
	TypeText Return
	assert "M3/PMS100".checkAllocationStatus is SUCCESS, "Allocation status in PMS100"
	(*Click (Image:"M3/PMS100/COMOOrderLine", WaitFor:3.3)*)	
	(*Click (Image:"CloseButton", WaitFor:344)*)	
end lookupSchedule

to lookup_3 coNumber
	WaitFor 10, "M3/PMS100/SortingOrderDropdown"
	Click "M3/PMS100/Sortingorderoption5"
	Click "M3/PMS100/5SingleRefOrdI"
	
	TypeText endKey
	Click "M3/PMS100/Viewdrop"
	Click "M3/PMS100/view05"
	Click "M3/PMS100/05001RefOrdPr"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS100/Reforderno"
	TypeText coNumber
	TypeText Return
	
end lookup_3


to lookup_4 coNumber
	WaitFor 10, "M3/PMS100/Sortingorder04"
	Click  "M3/PMS100/SortOptionRefOrdProd4"
	TypeText endKey
	Click "M3/PMS100/Viewdropdownoption04002"
	Click "M3/PMS100/04002ActualStartFinishc"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS100/Reforderno"
	TypeText coNumber
	TypeText Return
end lookup_4	

to openDeliveryToolbox
	Click "M3/PMS100/HighlightCO"
	Click "M3/PMS100/DeliveryToolboxLink"
end openDeliveryToolbox

to checkDeliveryStatus
	repeat 4 minutes
		if imageFound(5, "M3/PMS100/DeliveryStatus05") then
			Log "Delivery status is 5"
			
			return SUCCESS
			
			
		end if
		Click "M3/PMS100/Refresh"
	End repeat
	
end checkDeliveryStatus

to printShopTraveler scheduleNumber
	Click (Image:"M3/PMS100/MinimizePanel", WaitFor:103)
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "Mforms://PMZ440"
	Click "M3/Home/SearchSubmit"
	Click "M3/PMS100/Scheduleno440"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText scheduleNumber
	Click "M3/PMS100/Scheduleno440B"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText scheduleNumber
	Click (300,400)
	TypeText homeKey
	repeat 2 times
		TypeText downArrow
	end repeat
	TypeText Return
	Click "M3/OIS300/NextButton"
	Click "M3/PMS100/ConfirmOutput"
	Click "M3/PMS100/ExitButton"
	Click "M3/PMS100/ReOpenLink"
end printShopTraveler

function checkAllocationStatus
	repeat 4 minutes
		if imageFound(5,"M3/PMS100/COMOOrderLine") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkAllocationStatus

to pick
	WaitFor 8.0, "M3/PMS100/MaterialSts33Allocated"
	Click "M3/PMS100/DeliveryToolboxLink"
set deliveryNumber to ReadText((imageLocation("M3/PMS100/MONumberA")+(0,42), imageLocation("M3/PMS100/MONumberB") + (59,56)))
	Click "M3/PMS100/ReleaseforPickLink"
	assert "M3/PMS100".checkPickingListsImage is SUCCESS, "Delivery status update in delivery toolbox"
	Click "M3/PMS100/50PickingListsCreated"
	Click "M3/PMS100/PickingListsLink"
	KeyDown ControlKey
	repeat 6 times
		TypeText "="
	end repeat
	KeyUp ControlKey
	Click "M3/PMS100/MWS420B1OrderLine"
	Click "M3/PMS100/ConfirmIssuesLink"
	assert "M3/PMS100".checkPickingStatusImage is SUCCESS, "Picking status update in picking lists"
	KeyDown ControlKey
	repeat 6 times
		TypeText "-"
	end repeat
	KeyUp ControlKey
end pick

function checkPickingStatusImage
	repeat 2 minutes
		if imageFound(5,"M3/PMS100/PickingStatus90") then
			Log "Image found"
			return SUCCESS
		end if
		RightClick "M3/PMS100/MWS420B1OrderLine"
		Click "M3/PMS100/ConfirmIssuesLink"
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkPickingStatusImage

function checkPickingListsImage
	repeat 2 minutes
		if imageFound(5,"M3/PMS100/50PickingListsCreated") then
			Log "Image found"
			return SUCCESS
		end if
		Click "M3/PMS100/DeliveryOrderLine"
		
		Click "M3/PMS100/ReleaseforPickLink"
		Click "M3/PMS100/Refresh"
	end repeat
	Log "Image not found"
	return FAIL
end checkPickingListsImage

to recordMO
	Click "M3/PMS100/COMOOrderLine"
	DoubleClick "M3/PMS100/MONumberOrderLine"
	Wait 3
	DoubleClick "M3/PMS100/MONumber"
	TypeText controlKey, "c"
	Click "M3/OIS101/WindowsButton"
	if ImageFound(5, "M3/OIS101/WindowsSearchField") 
		Click "M3/OIS101/WindowsSearchField"
	else
		Click (30,700)
	end if
	TypeText controlKey, "v"
	repeat 2 times
		TypeText spacebar
	end repeat
	set moNumber to ReadText(((12,695),(75,711)))
	Log moNumber
	Click "M3/OIS101/WindowsButton"
	Click "M3/PMS100/BackButton"
	return moNumber
end recordMO

to close
	Click "M3/PMS100/CloseButton"
end close