to open
	WaitFor 30, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PMS170"
	Click "M3/Home/SearchSubmit"
end open

to lookup coNumber
	Click (Image:"M3/PMS170/Actions", WaitFor:15)
	Click "M3/PMS170/Settings"
	Click "M3/PMS170/Facility"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText "061"
	TypeText Return
	WaitFor 10, "M3/PMS170/Sortingorder_2"
	Click (780, 113)
	TypeText homeKey
	Click "M3/PMS170/SortingOrder3"
	Click (961,113)
	TypeText endKey
	Click "M3/PMS170/View51Dropdown"
	Click "M3/PMS170/ResponsibleField"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS170/Product_OrderLine"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PMS170/RefOrderNoField"
	TypeText coNumber
	TypeText Return
end lookup


To select_Product product
	WaitFor 10,  "M3/PMS170/Product_OrderLine"
	Click "M3/PMS170/Product_OrderLine"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText product
	TypeText Return
	click "M3/PMS170/IApply"
	If Imagefound("M3/PMS170/COnumber_select") then
		click "M3/PMS170/COnumber_select"
		waitfor 05, "M3/PMS170/COnumber_select"
		logSuccess "Product are displayed"
	else
		Logerror "Products are not displayed"
	End If
End select_Product

To change_line_status
	Click "M3/PMS170/OrderLine"
	If Imagefound("M3/PMS170/Change_Line") then
		click "M3/PMS170/Change_Line"
		If imagefound("M3/PMS170/Structuretype") then
			click "M3/PMS170/Structuretype"
			wait 5
			TypeText controlKey, "a"
			TypeText deleteKey
			TypeText "003"
			TypeText Return
			wait 2
			LogSuccess "Line Status Has Changed"
			(*click "M3/PMS170/Next_Image"
			if Imagefound("M3/PMS170/Next_Image") then
				click "M3/PMS170/Next_Image"
			end if
			wait 10*)
			
		Else
			throw "Error","Could not find M3/PMS170/Structuretype image in M3/PMS170 script, function change_line_status"
		End If        
	else
		throw "Error","Could not find M3/PMS170/Change_Line image in M3/PMS170 script, function change_line_status"
	End If
	if ImageFound("M3/PMS170/PMS170ELabel")then
		click "M3/PMS170/Next_Image"
	end if
End change_line_status



to create_schedule_number scheduleNumber

	Click "M3/PMS170/Related"
	Click "M3/PMS170/AddScheduleNumber_1"
	Click "M3/PMS170/SchednoField"
	click "M3/PMS170/WorkWith_Sh"
	wait 4
	click "M3/PMS170/Schedno_Sh"
	TypeText controlKey, "a" 
	TypeText deletekey
	TypeText scheduleNumber
	TypeText Return
	click"M3/PMS170/Create_sh"
	wait 3
	TypeText "Testing"
	Click "M3/PMS170/NextButton"
	Wait 3
	Click (Image:"M3/PMS170/CloseScheduleButton", WaitFor:32)
	Wait 3
	RightClick "M3/PMS170/OrderLine"
	Click "M3/PMS170/RelatedOptions"
	Click "M3/PMS170/AddScheduleNumber"
	TypeText scheduleNumber
	TypeText Return
	Click "M3/PMS170/ScheduleLine"
	Click "M3/PMS170/SelectScheduleButton"
	
end create_schedule_number


to createScheduleNumber
	put DataStore.getAndIncrementScheduleCounter into count
	put 10009212017+(100000000*count) into scheduleNumber
	log "New schedule number: " & scheduleNumber
	return scheduleNumber
end createScheduleNumber

to scheduleNew scheduleNumber
	RightClick "M3/PMS170/OrderLine"
	Click  "M3/PMS170/Related"
	Click  "M3/PMS170/AddScheduleNumber_1"
	
	TypeText f4
	TypeText scheduleNumber
	(*TypeText scheduleNumber*)
	Click "M3/PMS170/CreateLink"
	TypeText "US-Gear-06"
	Click "M3/PMS170/NextButton"
	Wait 3
	Click (Image:"M3/PMS170/CloseScheduleButton", WaitFor:32)
	Wait 3
	RightClick "M3/PMS170/OrderLine"
	Click "M3/PMS170/RelatedOptions"
	Click "M3/PMS170/AddScheduleNumber"
	TypeText scheduleNumber
	TypeText Return
	Click "M3/PMS170/ScheduleLine"
	Click "M3/PMS170/SelectScheduleButton"
end scheduleNew

to releaseMO
	RightClick "M3/PMS170/OrderLine"
	Click "M3/PMS170/RelatedOptions"
	Click "M3/PMS170/ReleaseButton"
end releaseMO

to recordProdNum
	wait 3
	put ReadText(((102,387),(161,399))) into prodNum
	log prodNum
	return prodNum
end recordProdNum

to close
	Click (Image:"M3/PMS170/ClosePMS170Button", WaitFor:117)
end close