to open
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PPS310"
	Click  "M3/Home/SearchSubmit"
end open

to poReceipt

	Click "M3/PPS310/WarehouseField"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click "M3/PPS310/ResponsibleField"
	TypeText controlKey, "a"
	TypeText deleteKey
	Click  "M3/PPS310/receiving number",240001
	
	TypeText Return
	
end poReceipt

to captureQuantity
	wait 5
	//set quantity to ReadText(((329,354),(343,363)))
	//put readtext(260,364,283,376) into quantity
	put  ReadText(350,387)into RMquanty
	put readtext (("M3/PPS300/PPS310/ReceivedqtyLT"),("M3/PPS300/PPS310/ReceivedqtyRB")) into quantity
	log quantity
end captureQuantity

to enterApprovedQuantity quantity
	Click "M3/PPS300/PPS310/Approvedqty"
	typetext  quantity
	logsuccess "quantity is logged as:- "&quantity
	click "M3/PPS300/Next"
	//click "M3/PPS300/Actions"
	//click  "M3/PPS300/ConfirmUpdateF"
	wait 5
	click "M3/PPS300/previousbutton"
	wait 2
	click "M3/PPS300/Confirmoutput"
	//Click "M3/PPS300/PPS310/XClose"	
end enterApprovedQuantity


