to openPPS320
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PPS320"
	Click  "M3/Home/SearchSubmit"
end openPPS320

to enterrecievingNumber ReciveNumber
	repeat 30 times
		wait 1
		if ImageFound("M3/PPS320/PPS320A")  then exit repeat
		if Imagefound("M3/PPS320/PPS320B1") then
			Click "M3/PPS300/Actions"
			Click "M3/PPS300/PPS310/SettingsF13"
			WaitFor 45, "M3/PPS320/PPS320PTitle"
			Click "M3/PPS300/PPS310/Openingpanel"
			Typetext upArrow
			Typetext return
			Click "M3/PPS300/Next"
		end if
	end repeat
	WaitFor 45, "M3/PPS320/PPS320A"
	Click "M3/PPS320/Receivingno_1"
	TypeText  controlkey, "a"
	TypeText deleteKey
	typetext ReciveNumber
	Click "M3/PPS320/Next"
end enterrecievingNumber

to enterStoredQty MPF
	Click "M3/PPS320/Location_1"
	typetext MPF
	click "M3/PPS300/Next"
	wait 4
	click "M3/PPS300/previousbutton"
	wait 4
	click "M3/PPS300/Confirmoutput"
end enterStoredQty








