to openpoNumber
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PPS300"
	Click "M3/Home/SearchSubmit"
end openpoNumber



to poReceipt poNumber, WHNumber
	Click "M3/PPS300/WarehouseField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText WHNumber
	//TypeText Return
	//Click "M3/PPS300/ResponsibleField"
	//TypeText controlKey, "a"
	//TypeText deleteKey
	//TypeText Return
	Click "M3/PPS300/PONumberField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText poNumber
	//TypeText Return
end poReceipt


to delynoteno poNumber
	click "M3/PPS300/Delynoteno"
	typetext controlkey,"a"
	typetext deletekey
	typetext PoNumber
end delynoteno

to recordReceivingNo
	Click "M3/PPS300/Receivingno"
	put  ImageLocation ("M3/PPS300/Receivingno") into loc
	Put loc+(-5,-20) into L1
	Put loc+(100,20) into L2
	put  ReadText((L1), (L2)) into ReciveNumber
	Log ReciveNumber
	return ReciveNumber
end recordReceivingNo

to searchlineitem ItemNumber
	wait 5
	Click "M3/PPS300/EnterItemnumber"
	typetext ItemNumber
	Click "M3/PPS300/Apply_1"
	wait 3
end searchlineitem

to captureremainingquantity
	//put readtext(ImageLocation("M3/PPS300/Remainingquant")) into RMquanty
	Click "M3/PPS300/SelectItemnumber"
	//put  ReadText(265,376,313,393)into RMquanty
	put  ReadText(354,377,382,395)into RMquanty
	if RMquanty <> "" then
		logsuccess "recievedquantity is:- "&RMquanty
		return RMquanty
	else
		logerror "recievedquantity is unable to find"
	end if
end captureremainingquantity

To EnterRecivedQuan RMquanty
	Click "M3/PPS300/Reevedqty"
	TypeText RMquanty
	wait 3
	Click "M3/PPS300/Next"
End EnterRecivedQuan

to enterRecievingNumberinPPS310 ReciveNumber
	"M3/PPS310".open
	if ImageFound(30, "M3/PPS300/PPS310/PPS310A_1") then 
		
		click "M3/PPS300/PPS310/Receivingno"
		TypeText  controlkey, "a"
		TypeText deleteKey
		Typetext ReciveNumber
		//TypeText Return
		Click "M3/PPS300/Next"
		Logsuccess "Reciving Number entered in PPS310 was :- "& ReciveNumber
		wait 4
	else if Imagefound("M3/PPS300/PPS310/PPS310B1") then
		Click "M3/PPS300/Actions"
		Click "M3/PPS300/PPS310/SettingsF13"
		wait 5
		Click "M3/PPS300/PPS310/Openingpanel"
		Typetext upArrow
		Typetext return
		Click "M3/PPS300/Next"
		wait 4
		click "M3/PPS300/PPS310/Receivingno"
		TypeText  controlkey, "a"
		TypeText deleteKey
		Typetext ReciveNumber
		//TypeText Return
		Click "M3/PPS300/Next"
		wait 4
		Logsuccess "Reciving Number entered in PPS310 was :- "& ReciveNumber
	else
		Logerror "Reciving Number not entered in PPS310"
		
	End if
	
end enterRecievingNumberinPPS310




















