to openpoNumber
	WaitFor 20, "M3/Application/inforSmartOfficeTitle"
	Click (Image:"M3/Home/SearchField", WaitFor:60)
	TypeText "PPS300"
	Click "M3/Home/SearchSubmit"
end openpoNumber

to poReceipt poNumber
	Click "M3/PPS300/WarehouseField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText "06Y"
	TypeText Return
	Click "M3/PPS300/ResponsibleField"
	TypeText controlKey, "a"
	TypeText deleteKey
	TypeText Return
	Click "M3/PPS300/PONumberField"
	TypeText poNumber
	TypeText Return"M3/Home/SearchSubmit"
end poReceipt

to close

end close

to delynoteno poNumber
	click "M3/PPS300/Delynoteno"
	typetext controlkey,"a"
	typetext deletekey
	typetext PoNumber
end delynoteno