

To ATPcheck
	Click "M3/PMS170/OrderLine"
	wait 2
	Click "M3/PMS170/Related"
	wait 2
	Click "M3/RPS010/CheckMaterialsCTRL12"
	If ImageFound(10,"M3/RPS010/RPS010B1") then
		Put ReadText((426,382), (448,391)) into ReqQuan
		Put ReadText((468,382), (501,391)) into ATPQuan
		Click "M3/RPS010/XClose"
		wait 10
		if ReqQuan <= ATPQuan then
			LogSuccess "Requested Quantity is Available in ATP "
			return SUCCESS
			Put "1" into ReqQuan
			Return ReqQuan
		else
			LogError "Requested Quantity is NOT Available in ATP"
			return FAIL
			Put "2" into ATPQuan1
			return ATPQuan1
		End If
	End If
	
	If ATPQuan is blank then
		Put "0" into ATPQuan
		set ATPQuan to ATPQuan1
		return ATPQuan1
	End If
End ATPcheck


to inventoryCheck
	if imageFound (5, "M3/PMS170/PMS170BcoLineHeader")
		put imageLocation("M3/PMS170/PMS170BcoLineHeader") into loc
		log loc
		put ReadText((loc)+(10,54)) into temp
		Click((loc)+(10,54))
		wait 1
		TypeText controlKey ,"12"
		If ImageFound(10,"M3/RPS010/RPS010B1")
			
			"M3/Application".checkZoomLevel 110
			if imageFound (3, "M3/RPS010/ReqdQty") then put rectangleReadWithRefrImage("M3/RPS010/ReqdQty",-26,47,42,63 ) into ReqQuan
			log ReqQuan &" : is the Required Quantity for CO : " &coNum
			if imageFound (3,"M3/RPS010/AtpQty") then put rectangleReadWithRefrImage("M3/RPS010/AtpQty","-6",47,64,63 ) into ATPQuan
			log ATPQuan &" : is the Inventory Quantity for CO : " &coNum
			"M3/Application".checkZoomLevel 90
			
			Click image:"M3/RPS010/XClose",waitFor: 5
			
			if ATPQuan is empty
				return "noStock"
				exit handler
			end if
			
			if ReqQuan is less than ATPQuan or if ReqQuan equals ATPQuan
				LogSuccess "Stock Available in Inventory "
				return "inStock"
			else
				LogWarning "Inventory Shortage - Requested Quantity not Available in ATP"
				return "noStock"
			End If
		end if
	else
		Log "Product Line Item not displayed"
	End If		
end inventoryCheck


--   >>>>> This Function Can be used by passing image and the desired xordinates which needs to be tweaked from that Image location to read from rectangle. >>>>>>>>>
to rectangleReadWithRefrImage img,x1,y1,x2,y2
	put ImageLocation(img) into Loc
	put item 1 of Loc into X
	put item 2 of Loc into Y
	set topLeft to ((X+(x1)),(Y+(y1)))
	set botmRight  to ((X+(x2)),(Y+(y2)))
	Put ReadText(topLeft,botmRight) into someVar
	Return someVar
end rectangleReadWithRefrImage 







