to getAndIncrementScheduleCounter
	set caseBook to Workbook(ResourcePath("1-Validation.xlsx"))
	set worksheet2 to caseBook.Worksheet("Sheet2")
	put Cell(worksheet2, "B1") into count
	put count + 1 into count
	put count into Cell(worksheet2, "B1")
	log "Cell value: " & Cell(worksheet2, "B1")
	return count
end getAndIncrementScheduleCounter

to recordRun coNumber, moNumber, scheduleNumber, deliveryNumber
	set caseBook to Workbook(ResourcePath("1-Validation.xlsx"))
	set worksheet2 to caseBook.Worksheet("Sheet2")
	set worksheet3 to caseBook.Worksheet("Sheet3")
	put Cell(worksheet2, "B2") into index
	put coNumber into Cell(worksheet3, "A" & index)
	put moNumber into Cell(worksheet3, "B" & index)
	put scheduleNumber into Cell(worksheet3, "C" & index)
	put deliveryNumber into Cell(worksheet3, "D" & index)
	put index+1 into Cell(worksheet2, "B2")
end recordRun

to setGlobalsScript1
	global username
	global password
	global customerNum
	global coType
	global PO
	global itemCode
	global productQuantity
	global DCAUser
	global DCAPswrd
	set ExcelFile to workbook(ResourcePath("1-Datastore.xlsx"))
	set worksheet to ExcelFile.Worksheet("Login")
	Put Cell(worksheet,"A2") into username
	Put Cell(worksheet,"B2") into password
	Put Cell(worksheet,"C5") into customerNum
	Put Cell(worksheet,"D2") into coType
	Put Cell(worksheet,"E4") into PO
	Put Cell(worksheet,"F5") into itemCode
	Put Cell(worksheet,"G2") into productQuantity
	Put Cell(worksheet,"H2") into DCAUser
	Put Cell(worksheet,"I2") into DCAPswrd
	Log "test " & username
end setGlobalsScript1

to setDataScript1 dataIndex
	global custNum
	global custPO
	global tag
	global delTerm
	global delMeth
	global style
	global color
	global ConfigCode
	global BlnktAgrmnt
	global Priority
	global trnsctnResn
	set ExcelFile to workbook(ResourcePath("1-data.xlsx"))
	set worksheet to ExcelFile.Worksheet("Input")
	put Cell(worksheet, "A" & dataIndex) into custNum
	put Cell(worksheet, "E" & dataIndex) into custPO
	put Cell(worksheet, "F" & dataIndex) into tag
	put Cell(worksheet, "G" & dataIndex) into delTerm
	put Cell(worksheet, "H" & dataIndex) into delMeth
	put Cell(worksheet, "I" & dataIndex) into Priority
	put Cell(worksheet, "J" & dataIndex) into style
	put Cell(worksheet, "K" & dataIndex) into color
	put Cell(worksheet, "W" & dataIndex) into ConfigCode
	put Cell(worksheet, "X" & dataIndex) into blnktAgrmnt
	put Cell(worksheet, "Z" & dataIndex) into trnsctnResn
end setDataScript1

to getCustomerNo 
	set caseBook to Workbook(ResourcePath("1-CustomGear-Input.xlsx"))
	set worksheet2 to caseBook.Worksheet("Stock Input")
	put Cell(worksheet2, "A2") into customerNumber
	Log customerNumber 
	return customerNumber
end getCustomerNo

to setLoginVariables index
	global username
	global password
	set ExcelFile to workbook(ResourcePath("Logins.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	Put Cell(worksheet,"A" & index) into username
	Put Cell(worksheet,"B" & index) into password
end setLoginVariables

to setDataScript2 dataIndex
	global coNum
	set ExcelFile to workbook(ResourcePath("2-data.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	put Cell(worksheet, "A" & dataIndex) into coNum
end setDataScript2

to setSimpleData fileName, sheetName, dataIndex
	global data
	set excelFile to workbook(ResourcePath(fileName))
	set worksheet to ExcelFile.Worksheet(sheetName)
	put Cell(worksheet, "A" & dataIndex) into data
	return data
end setSimpleData

to setDataScript3
	global customerNumber
	global coType
	global PO
	global itemCode
	global quantity
	global coNumber
	global product
	global count
	set ExcelFile to workbook(ResourcePath("ZCustomaization.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	set worksheet1 to Excelfile.Worksheet("Sheet2")
	Put Cell(worksheet, A2) into customerNumber
	Put Cell(worksheet, B2 ) into coType 
	Put Cell(worksheet, C2) into PO
	Put Cell(worksheet, D2) into itemCode
	Put Cell(worksheet, E2) into quantity
	Put Cell(worksheet, A2) into coNumber 
	Put Cell(worksheet, D2) into product
	Put Cell(worksheet1, B1) into count
end setDataScript3

To SetDataScript6 dataIndex
	global customerNumber
	global coType
	global PO
	global TagField
	global DeliveryTerm
	global DeliveryMethod
	global WHNumber
	global itemCode
	global quantity
	global PromoCod
	global TranctionResonCode
	global BlanketAgreement
	set ExcelFile to workbook(ResourcePath("6-GenericStockOrder.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	Put Cell(worksheet, "A" & dataIndex) into customerNumber
	Put Cell(worksheet, "B" & dataIndex) into coType
	Put Cell(worksheet, "C" & dataIndex) into  PO
	Put Cell(worksheet, "D" & dataIndex) into TagField
	Put Cell(worksheet, "E" & dataIndex) into DeliveryTerm 
	Put Cell(worksheet, "F" & dataIndex) into DeliveryMethod
	Put Cell(worksheet, "G" & dataIndex) into WHNumber
	Put Cell(worksheet, "H" & dataIndex) into itemCode
	Put Cell(worksheet, "I" & dataIndex) into quantity
	Put Cell(worksheet, "J" & dataIndex) into PromoCod
	Put Cell(worksheet, "K" & dataIndex) into TranctionResonCode
	Put Cell(worksheet, "L" & dataIndex) into BlanketAgreement
End SetDataScript6

To SetDataScript7 dataIndex
	global customerNumber
	global SalesHold
	global PO
	global TagField
	global DeliveryTerm
	global DeliveryMethod
	global WHNumber
	global itemCode
	global quantity
	global PromoCod
	global TranctionResonCode
	global BlanketAgreement
	global priority
	global ConfigurationNo
	set ExcelFile to workbook(ResourcePath("7-data.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	Put Cell(worksheet, "A" & dataIndex) into customerNumber
	Put Cell(worksheet, "B" & dataIndex) into SalesHold
	Put Cell(worksheet, "C" & dataIndex) into  PO
	Put Cell(worksheet, "D" & dataIndex) into TagField
	Put Cell(worksheet, "E" & dataIndex) into DeliveryTerm 
	Put Cell(worksheet, "F" & dataIndex) into DeliveryMethod
	Put Cell(worksheet, "G" & dataIndex) into WHNumber
	Put Cell(worksheet, "H" & dataIndex) into itemCode
	Put Cell(worksheet, "I" & dataIndex) into quantity
	Put Cell(worksheet, "J" & dataIndex) into PromoCod
	Put Cell(worksheet, "K" & dataIndex) into TranctionResonCode
	Put Cell(worksheet, "L" & dataIndex) into BlanketAgreement
	Put Cell(worksheet, "M" & dataIndex) into priority
	Put Cell(worksheet, "N" & dataIndex) into ConfigurationNo
End SetDataScript7

to SetDataScript8 dataIndex
	global InvoiceNumber
	global InvoiceDate
	global OrderNum
	global WHS
	global DeliveryNum
	global CustomerPO
	global AccountNum
	global ItemNum
	global Description
	global ShippedQty
	global UM
	global UnitPrice
	global Disc1
	global Disc2
	global Disc3
	global CstmChanges
	global NetPrice
	global Extended
	global TotalShippedQty
	global NetOrderTotal
	global ShippingHandlingTotal
	global TotalInvoice
	
	set ExcelFile to workbook(ResourcePath("8-data.xlsx"))
	set worksheet to ExcelFile.Worksheet("Sheet1")
	put Cell(worksheet, "A" & dataIndex) into InvoiceNumber
	put Cell(worksheet, "B" & dataIndex) into InvoiceDate
	put Cell(worksheet, "C" & dataIndex) into OrderNum
	put Cell(worksheet, "D" & dataIndex) into WHS
	put Cell(worksheet, "E" & dataIndex) into DeliveryNum
	put Cell(worksheet, "F" & dataIndex) into CustomerPO
	put Cell(worksheet, "G" & dataIndex) into AccountNum
	put Cell(worksheet, "H" & dataIndex) into ItemNum
	put Cell(worksheet, "I" & dataIndex) into Description
	put Cell(worksheet, "J" & dataIndex) into ShippedQty
	put Cell(worksheet, "K" & dataIndex) into UM
	put Cell(worksheet, "L" & dataIndex) into UnitPrice
	put Cell(worksheet, "M" & dataIndex) into Disc1
	put Cell(worksheet, "N" & dataIndex) into Disc2
	put Cell(worksheet, "O" & dataIndex) into Disc3
	put Cell(worksheet, "P" & dataIndex) into CstmChanges
	put Cell(worksheet, "Q" & dataIndex) into NetPrice
	put Cell(worksheet, "R" & dataIndex) into Extended
	put Cell(worksheet, "S" & dataIndex) into TotalShippedQty
	put Cell(worksheet, "T" & dataIndex) into NetOrderTotal
	put Cell(worksheet, "U" & dataIndex) into ShippingHandlingTotal
	put Cell(worksheet, "V" & dataIndex) into TotalInvoice
	
end SetDataScript8




(*
to ConfigValues 
set ExcelFile to workbook(ResourcePath("Datastore.xlsx"))
set worksheet to ExcelFile.Worksheet("Login")
Put Cell(worksheet,A2) into UserName
Put Cell(worksheet,B2) into Password
Put Cell(worksheetC2) into  customerNumber 
Put Cell(worksheet,D2) into  coType
end ConfigValues
*)
