(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-08-08 09:53:56
  From session:  untitled session
  Captured on:  2017-08-08 09:52:22
  From server:  USHQV043
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0002"
TypeText "ajenkins"
Click "image0004"
TypeText "A"
MoveTo "image0003"
KeyUp "a"
TypeText "cushnet#"
MoveTo "image0005"
TypeText "1"
Click "LocationI500AcushnetCanada500H"
Click "10062USVistaCustomBag1335Sycam"
Click "Login"
Click "image0006"
Click "image0007"
TypeText "A"
MoveTo "image0008"
KeyUp "a"
TypeText "j",Backspace,Backspace
MoveTo "image0009"
TypeText "A"
MoveTo "image0010"
KeyUp "a"
TypeText "cushnet#"
MoveTo "image0011"
KeyUp "3"
TypeText "1",Return
Click "image0012"
