//Flagship login
to open
	Click "Flagship/Login/IELink"
	Click (Image:"Flagship/Login/FlagshipLink", WaitFor:68)
end open

to login
	DoubleClick "Flagship/Login/UserNameField"
	TypeText "QUALTEST1"
	Click "Flagship/Login/PasswordField"
	TypeText "QUALTEST1"
	Click "Flagship/Login/LogInButton"
end login

to ship deliveryNumber
	Click "Flagship/Login/ShipLink"
	Click "Flagship/Login/WarehouseLink"
	Wait 5
	TypeText "00" & deliveryNumber & "001"
	(*TypeText "0013140395001"*)
	TypeText Return
	Wait 7
	Click "Flagship/Ship/ProNumber"
	TypeText "US-Gear-06"
	Wait 5
	Click "Flagship/Ship/ShipButton"
	Wait 10
	Click "Flagship/Ship/ExitPackingLabelButton"
	Wait 3
	Click "Flagship/Login/ShipLink"
	Wait 3
	Click "Flagship/Close/CloseLink"
	Wait 3
	Click "Flagship/Close/SearchButton"
	Wait 3
	Click "Flagship/Close/SHIPCheckbox"
	Wait 3
	Click "Flagship/Close/CloseOrderButton"
	Wait 5
end ship

to close
	Click (Image:"Flagship/Close/LogOut", WaitFor:6.9)
	Click "Flagship/Close/ExitIE"
end close

