to open
	Click (Image:"DCA/DCAIcon", WaitFor:30)
end open

to login
	TypeText "ajenkins"
	TypeText Return
	TypeText "Acushnet#1"
	TypeText Return
end login

to manufacture moNumber
	TypeText 1
	TypeText Return
	TypeText moNumber
	TypeText Return
	WaitFor 11.1, "DCA/TransactionComplete"
	TypeText f1
	TypeText 2
	TypeText Return
	TypeText moNumber
	TypeText Return
	WaitFor 10, "DCA/TransactionComplete"
end manufacture

to close
	RightClick "DCA/DCAScreen"
	Click "DCA/DCAExitLink"
end close