to open
	Wait 10
	Click (Image:"DCA/DCAIcon", WaitFor:30)
	if (ImageFound(5, "DCA/USERID")) then
		TypeText ajenkins
		TypeText Return
		TypeText "Acushnet#1"
		TypeText Return
	end if
end open

to login UserName, Password
	TypeText UserName
	TypeText Return
	TypeText Password
	TypeText Return
end login

to manufacture moNumber
	TypeText f1
	TypeText 1
	TypeText Return
	Log "Starting MO: " & moNumber
	TypeText moNumber
	TypeText Return
	(*WaitFor 11.1, "DCA/TransactionComplete"*)
	assert "Other/DCA".checkTransactionStatusA(moNumber) is SUCCESS, "MO start in DCA"
	TypeText f1
	TypeText 2
	TypeText Return
	Log "Finishing MO: " & moNumber
	TypeText moNumber
	TypeText Return
	(*WaitFor 10, "DCA/TransactionComplete"*)
	assert "Other/DCA".checkTransactionStatusB(moNumber) is SUCCESS, "MO finish in DCA"
end manufacture

function checkTransactionStatusA moNumber
	repeat 3 minutes
		if imageFound(10,"DCA/TransactionComplete") then
			Log "Image found"
			return SUCCESS
		end if
		TypeText f1
		TypeText 1
		TypeText Return
		TypeText moNumber
		TypeText Return
	end repeat
	Log "Image not found"
	return FAIL
end checkTransactionStatusA

function checkTransactionStatusB moNumber
	repeat 3 minutes
		if imageFound(60,"DCA/TransactionComplete") then
			Log "Image found"
			return SUCCESS
		end if
		TypeText f1
		TypeText 2
		TypeText Return
		TypeText moNumber
		TypeText Return
	end repeat
	Log "Image not found"
	return FAIL
end checkTransactionStatusB

to close
	RightClick "DCA/DCAScreen"
	Click "DCA/DCAExitLink"
end close