## Click and open the desktop application for MetaViewer
To openMV
	doubleclick Image:"MetaViewer/DesktopIcon", Waitfor:45
end openMV


## Login
To loginMV username, password
	click "MetaViewer/MVUsername"
	TypeText username
	click "MetaViewer/MVPasswrod"
	TypeText password
	TypeText ReturnKey
End loginMV


## Search for the Refernce Number and open up the pdf
To lookupMV NumberMV
	Wait 5
	TypeText NumberMV
	TypeText ReturnKey
	
	repeat 100 times
		if ImageFound("MetaViewer/MVErrorMessage")
			Click "MetaViewer/MVErrorOK"
			CloseMV
			throw "Error","MetaViewer search timed out"
		end if
		if ImageFound("MetaViewer/MetaViewerTree/PDFicon") then exit repeat
		Wait 3
	end repeat
	
	Log "Search successful"
	DoubleClick "MetaViewer/MetaViewerTree/FinalFolder"
	DoubleClick "MetaViewer/MetaViewerTree/SubFolder1"
	DoubleClick "MetaViewer/MetaViewerTree/SubFolder2"
	DoubleClick "MetaViewer/MetaViewerTree/SubFolder3"
	DoubleClick "MetaViewer/MetaViewerTree/PDFicon"
	
End lookupMV

## Puts in the data from the PDF into variables for us to use for comparing against the Excel
to validateInvoice
	
	wait 3
	click "MetaViewer/PDF/MVFullscreen"
	Wait 5
	WaitFor 45,"MetaViewer/PDF/Titleist"
	
	put "MetaViewer/PDF/" into path
	
	set InvoiceNoPDF to ReadText((86,314))
	Log (InvoiceNoPDF  & " is the Invoice Number")
	
	set OrderNoPDF to ReadText((90,343))
	Log (OrderNoPDF  & " is the Order Number")
	
	set WhsPDF to ReadText((173,343))
	if WhsPDF is "06Y" then set WhsPDF to "060"
	if WhsPDF is "06B" then set WhsPDF to "061"
	Log WhsPDF && "is the warehouse number"
	
	set customersPO to ReadText((437,345))
	Log customersPO && "is Customers PO"

	set AccountNoPayPDF to ReadText((745,342))
	Log (AccountNoPayPDF & " is the Account No of the Pay Account")
	
	set AccountNoShipPDF to ReadText((900,343))
	Log (AccountNoShipPDF & " is the Account No of the Ship Account")
	
	return (InvoiceNoPDF, OrderNoPDF, WhsPDF, AccountNoPayPDF, AccountNoShipPDF, customersPO)
	
end validateInvoice

to CloseMV
	Click "MetaViewer/PDF/MVClose"
end CloseMV