## Click and open the desktop application for MetaViewer
To openMV
	doubleclick "MetaViewer/DesktopIcon"
end openMV


## Login
To loginMV username, password
	click "MetaViewer/MVUsername"
	TypeText username
	click "MetaViewer/MVPasswrod"
	TypeText password
	TypeText ReturnKey
End loginMV


## Search for the Refernce Number and open up the pdf
To lookupMV NumberMV
	TypeText NumberMV
	TypeText ReturnKey
	put WaitUntilObjectExist("MetaViewer/MVErrorMessage", 30)
	
	Repeat 30 seconds
		if ImageFound (2, "MetaViewer/MVErrorMessage") then
			TypeText ReturnKey
		else
			exit repeat
		end if
	end repeat
	
	DoubleClick "MetaViewer/MetaViewerTree/MVAGUSTESTM3"
	DoubleClick "MetaViewer/MetaViewerTree/AGSUS13"
	DoubleClick "MetaViewer/MetaViewerTree/Test13.4Invoice"
	DoubleClick "MetaViewer/MetaViewerTree/FinalFolder"
	
	wait 3
	
	Repeat 30 seconds
		if ImageFound (2, "MetaViewer/MVErrorMessage") then
			TypeText ReturnKey
		else
			exit repeat
		end if
	end repeat
	
End lookupMV


## Waits for an object to appear and then the user can specify how long it should wait for
function WaitUntilObjectExist (myObject, timeout)
	wait 1
	log myObject
	log timeout
	put 0 into x
	
	repeat timeout times            
		if ImageFound (myObject) then
			add 1 to x
			exit repeat
		end if                    
	end repeat
	
	if x is 1 then
		Log "Successfully found Error Message"
	else if x is 0 then
		LogError "error occured while searching for object["&myObject&"]"
	end if
end WaitUntilObjectExist

## Puts in the data from the PDF into variables for us to use for comparing against the Excel
to validateInvoice
	
	put "MetaViewer/PDF/" into path
	
	set InvoiceNoPDF to ReadText((imageLocation (path&"InvoiceNo/InvoiceNo") +(-4,10), imageLocation (path&"InvoiceNo/InvoiceNo_1") +(73,20)))
	Log (InvoiceNoPDF  & " is the Invoice Number")
	
	set OrderNoPDF to ReadText((imageLocation (path&"OrderNo/OrderNo") +(-4,10), imageLocation (path&"OrderNo/OrderNo_1") +(73,20)))
	Log (OrderNoPDF  & " is the Order Number")
	
	set WhsPDF to ReadText((imageLocation (path&"Whs/Whs") +(-4,10), imageLocation (path&"Whs/Whs_1") +(45,23)))
	Log (WhsPDF  & " is the Whs")
	
	set InvoiceDatePDF to ReadText((imageLocation (path&"InvoiceDate/InvoiceDate") +(-4,10), imageLocation (path&"InvoiceDate/InvoiceDate_1") +(73,20)))
	Log (InvoiceDatePDF & " is the Invoice Date")
	
	set DeliveryNoPDF to ReadText((imageLocation (path&"DeliveryNo/DeliveryNo") +(-4,10), imageLocation (path&"DeliveryNo/DeliveryNo_1") +(73,20)))
	Log (DeliveryNoPDF & " is the Delivery Number")
	
	set ShipmentDatePDF to ReadText((imageLocation (path&"ShipmentDate/ShipmentDate") +(-4,10), imageLocation (path&"ShipmentDate/ShipmentDate_1") +(73,20)))
	Log (ShipmentDatePDF & " is the Shipment Date")	
	
	set CustomerPOPDF to ReadText((imageLocation (path&"CustomerPO/CustomerPO") +(-4,10), imageLocation (path&"CustomerPO/CustomerPO_1") +(73,20)))
	Log (CustomerPOPDF & " is the Customer PO")
	
	set OrderDatePDF to ReadText((imageLocation (path&"OrderDate/OrderDate") +(-4,10), imageLocation (path&"OrderDate/OrderDate_1") +(74,21)))
	Log (OrderDatePDF & " is the Order Date")
	
	set AccountNoPayPDF to ReadText((imageLocation (path&"AccountNo/AccountNo") +(-4,10), imageLocation (path&"AccountNo/AccountNo_1") +(74,21)))
	Log (AccountNoPayPDF & " is the Account No of the Pay Account")
	
	set AccountNoShipPDF to ReadText((imageLocation (path&"AccountNo/AccountNo") +(120,10), imageLocation (path&"AccountNo/AccountNo_1") +(226,21)))
	Log (AccountNoShipPDF & " is the Account No of the Ship Account")
	
	set BagSandHPDF to ReadText((imageLocation (path&"BagSandH/BagSandH") +(8,160), imageLocation (path&"BagSandH/BagSandH_1") +(170,173)))
	Log ( "There is a Shipping handling charge because this text was found on the PDF: _" & BagSandHPDF & "_")
	
	return (InvoiceNoPDF, OrderNoPDF, WhsPDF, InvoiceDatePDF, DeliveryNoPDF, ShipmentDatePDF, CustomerPOPDF, OrderDatePDF, AccountNoPayPDF, AccountNoShipPDF, BagSandHPDF)
	
end validateInvoice